// UI strings. Dari (fa) is the primary language; English (en) is the fallback.
export const strings = {
  fa: {
    brandTagline: 'مستقیم با افغانی',
    welcomeTitle: 'تتر بخرید و بفروشید،',
    welcomeSub: 'بازار همتا‌به‌همتا با تضمین امانی — تتر فروشنده تا تأیید پرداخت شما نزد پلتفرم قفل می‌ماند.',
    createAccount: 'ایجاد حساب رایگان',
    haveAccount: 'حساب دارم — ورود',
    browseMarket: 'دیدن بازار بدون ورود',
    language: 'زبان',

    welcomeBack: 'خوش آمدید',
    loginSub: 'برای خرید و فروش تتر وارد حساب خود شوید.',
    registerTitle: 'ایجاد حساب',
    registerSub: 'نام کاربری و رمز عبور انتخاب کنید.',
    login: 'ورود',
    register: 'ثبت نام',
    username: 'نام کاربری',
    usernameHint: '۳ تا ۲۴ حرف انگلیسی، عدد یا _',
    displayName: 'نام نمایشی',
    phone: 'شماره موبایل',
    password: 'رمز عبور',
    passwordHint: 'حداقل ۸ حرف',
    showPassword: 'نمایش رمز',
    secureNote: 'اتصال رمزگذاری‌شده و تأیید دومرحله‌ای برای برداشت‌ها',
    back: 'بازگشت',
    close: 'بستن',

    greeting: 'سلام',
    totalBalance: 'موجودی کل',
    hideBalance: 'پنهان کردن موجودی',
    available: 'قابل استفاده',
    inEscrow: 'در امانت',
    approxAfn: '≈ {v} افغانی',
    deposit: 'واریز',
    withdraw: 'برداشت',
    buy: 'خرید',
    sell: 'فروش',
    bestBuy: 'بهترین قیمت خرید',
    bestSell: 'بهترین قیمت فروش',
    goMarket: 'رفتن به بازار',
    activeTrades: 'معامله‌های فعال',
    all: 'همه',
    recentActivity: 'فعالیت اخیر',
    noActivity: 'هنوز فعالیتی ندارید. با واریز تتر یا خرید از بازار شروع کنید.',

    market: 'بازار P2P',
    marketSub: 'معامله مستقیم با کاربران',
    buyUsdt: 'خرید USDT',
    sellUsdt: 'فروش USDT',
    amountAfnFilter: 'مبلغ مورد نظر به افغانی',
    filters: 'فیلترها',
    newOffer: 'آگهی جدید',
    trades: 'معامله',
    completion: 'تکمیل',
    perUsdt: 'برای هر USDT',
    availableAmt: 'موجود',
    limits: 'محدوده',
    noOffers: 'فعلاً آگهی‌ای با این شرایط نیست.',
    postFirstOffer: 'اولین آگهی را بگذارید',

    escrow: 'امانی',
    memberTrades: 'معاملات',
    payWindow: 'مهلت پرداخت',
    minutes: '{n} دقیقه',
    youPay: 'مبلغ پرداخت',
    youSell: 'مقدار فروش',
    youReceive: 'دریافت می‌کنید',
    inAfn: 'افغانی',
    max: 'حداکثر',
    fee: 'کمیشن',
    paymentMethod: 'روش پرداخت',
    sellerTerms: 'شرایط آگهی‌دهنده',
    escrowNote: 'تتر فروشنده تا پایان معامله در امانت پلتفرم قفل است.',
    buyAmount: 'خرید {v} USDT',
    sellAmount: 'فروش {v} USDT',
    loginToTrade: 'برای معامله وارد شوید',
    needAccountFor: 'برای فروش، ابتدا حساب دریافت {m} خود را در «حساب من» ثبت کنید.',

    order: 'سفارش',
    buyFrom: 'خرید از {n}',
    sellTo: 'فروش به {n}',
    payNow: 'مبلغ را پرداخت کنید',
    payNowSub: 'اگر تا پایان زمان پرداخت نکنید، سفارش خودکار لغو می‌شود.',
    waitBuyer: 'منتظر پرداخت خریدار',
    waitBuyerSub: 'پس از پرداخت خریدار، حساب خود را بررسی و تتر را آزاد کنید.',
    waitSeller: 'منتظر تأیید فروشنده',
    waitSellerSub: 'فروشنده پرداخت شما را بررسی می‌کند و تتر را آزاد می‌کند.',
    checkPayment: 'خریدار پرداخت کرد',
    checkPaymentSub: 'فقط پس از دیدن پول در حساب خود، تتر را آزاد کنید.',
    disputed: 'در حال داوری',
    disputedSub: 'پشتیبانی شواهد هر دو طرف را بررسی می‌کند. تتر تا تصمیم داور قفل می‌ماند.',
    stepPay: 'پرداخت',
    stepConfirm: 'تأیید فروشنده',
    stepReceive: 'دریافت',
    amountToPay: 'مبلغ قابل پرداخت',
    amountToReceive: 'مبلغ دریافتی شما',
    copy: 'کپی',
    copied: 'کپی شد',
    price: 'قیمت',
    receiveNet: 'دریافتی خریدار',
    recipientName: 'نام گیرنده',
    accountNumber: 'شماره حساب',
    noAccountInfo: 'فروشنده هنوز جزئیات حساب را ثبت نکرده — در گفتگو بپرسید.',
    payWarning: 'فقط از حساب به نام خودتان پرداخت کنید و در توضیحات پرداخت کلمهٔ «USDT» ننویسید.',
    releaseWarning: 'هرگز پیش از رسیدن پول به حساب خود تتر را آزاد نکنید. رسید عکس کافی نیست.',
    iPaid: 'پرداخت کردم',
    cancelOrder: 'لغو سفارش',
    confirmCancel: 'سفارش لغو شود؟ اگر پول فرستاده‌اید لغو نکنید.',
    release: 'پول را گرفتم — آزادسازی تتر',
    confirmRelease: 'آیا مطمئن هستید مبلغ {v} افغانی به حساب شما رسیده است؟ این کار قابل برگشت نیست.',
    openDispute: 'شکایت / داوری',
    disputeReason: 'دلیل شکایت',
    disputePlaceholder: 'چه اتفاقی افتاده؟ مثلاً: پول را فرستادم ولی فروشنده پاسخ نمی‌دهد.',
    submit: 'ثبت',
    cancel: 'انصراف',
    confirm: 'تأیید',
    chat: 'گفتگو',
    tradeDone: 'معامله با موفقیت انجام شد',
    addedToWallet: 'به کیف پول شما اضافه شد و قابل استفاده است.',
    soldDone: 'تتر فروخته شد و به خریدار رسید.',
    tradeCancelled: 'سفارش لغو شد',
    tradeCancelledSub: 'تتر امانی به فروشنده برگشت.',
    orderNo: 'شماره سفارش',
    counterparty: 'طرف معامله',
    paid: 'پرداخت شده',
    viewWallet: 'مشاهده کیف پول',
    newTrade: 'معامله جدید',

    online: 'آنلاین',
    writeMessage: 'پیام بنویسید…',
    send: 'ارسال',
    chatSafety: 'هرگز خارج از پلتفرم تتر نفرستید — پشتیبانی گفتگو را می‌بیند.',
    noMessages: 'هنوز پیامی نیست. سلام کنید!',
    sys_trade_opened: 'سفارش ایجاد شد · تتر فروشنده در امانت قفل شد',
    sys_trade_marked_paid: 'خریدار پرداخت را علامت زد · منتظر تأیید فروشنده',
    sys_trade_released: 'فروشنده تتر را آزاد کرد · معامله تکمیل شد',
    sys_trade_cancelled_by_buyer: 'خریدار سفارش را لغو کرد',
    sys_trade_expired: 'مهلت پرداخت تمام شد · سفارش لغو شد',
    sys_trade_disputed: 'شکایت ثبت شد · پشتیبانی بررسی می‌کند',
    sys_trade_resolved_buyer: 'داور به نفع خریدار تصمیم گرفت',
    sys_trade_resolved_seller: 'داور به نفع فروشنده تصمیم گرفت',

    wallet: 'کیف پول',
    network: 'شبکه',
    tether: 'تتر',
    history: 'تاریخچه',
    today: 'امروز',
    yesterday: 'دیروز',
    kind_deposit: 'واریز تتر',
    kind_withdraw_lock: 'درخواست برداشت',
    kind_withdraw_refund: 'برداشت رد شد · بازگشت',
    kind_withdrawal: 'برداشت ارسال شد',
    kind_offer_lock: 'قفل برای آگهی فروش',
    kind_offer_unlock: 'آزاد شدن آگهی',
    kind_trade_lock: 'قفل برای معامله',
    kind_trade_refund: 'بازگشت از معامله',
    kind_escrow_release: 'فروش تتر',
    kind_trade_receive: 'خرید تتر',
    status_pending: 'در حال بررسی',
    status_approved: 'تأیید شد',
    status_rejected: 'رد شد',
    status_sent: 'ارسال شد',

    depositUsdt: 'واریز USDT',
    tronNetwork: 'شبکهٔ ترون (TRC20)',
    onlyNetwork: 'تنها شبکهٔ پشتیبانی‌شده',
    depositAddress: 'آدرس واریز',
    depositWarning: 'فقط USDT روی شبکهٔ TRC20 بفرستید. ارسال از شبکه‌های دیگر مثل ERC20 یا BEP20 باعث از دست رفتن دارایی می‌شود.',
    afterSending: 'پس از ارسال، مقدار و شناسهٔ تراکنش (TxID) را وارد کنید',
    amount: 'مقدار',
    txid: 'شناسهٔ تراکنش (TxID)',
    paste: 'چسباندن',
    submitDeposit: 'ثبت واریز',
    depositSubmitted: 'واریز ثبت شد و پس از بررسی روی شبکه به موجودی شما اضافه می‌شود.',
    recentDeposits: 'واریزهای اخیر',

    withdrawUsdt: 'برداشت USDT',
    destAddress: 'آدرس مقصد',
    destHint: 'آدرس باید با حرف T شروع شود و روی شبکهٔ ترون باشد.',
    networkFee: 'کارمزد شبکه',
    totalDeducted: 'کسر از موجودی',
    destReceives: 'دریافتی مقصد',
    minWithdraw: 'حداقل برداشت: {v} USDT',
    confirmWithdraw: 'تأیید برداشت',
    withdrawNote: 'برداشت‌ها پس از بررسی امنیتی روی شبکه ارسال می‌شوند.',
    withdrawSubmitted: 'درخواست برداشت ثبت شد.',
    recentWithdrawals: 'برداشت‌های اخیر',

    createOffer: 'ایجاد آگهی',
    iWantBuy: 'می‌خواهم بخرم',
    iWantSell: 'می‌خواهم بفروشم',
    pricePerUsdt: 'قیمت هر USDT',
    marketBest: 'بهترین قیمت فعلی بازار: {v} ؋',
    totalToSell: 'مقدار کل برای فروش',
    totalToBuy: 'مقدار کل برای خرید',
    perTradeLimits: 'محدودهٔ هر معامله (افغانی)',
    min: 'حداقل',
    receiveMethods: 'روش‌های دریافت پول',
    payMethods: 'روش‌های پرداخت شما',
    buyerWindow: 'مهلت پرداخت خریدار',
    terms: 'شرایط معامله (اختیاری)',
    termsPlaceholder: 'مثلاً: فقط از حساب به نام خودتان پرداخت کنید.',
    lockNote: '{v} USDT تا بسته شدن آگهی در امانت قفل می‌شود.',
    publishOffer: 'انتشار آگهی',
    offerPublished: 'آگهی منتشر شد.',
    missingAccounts: 'برای این روش‌ها حساب دریافت ثبت نکرده‌اید: {m}',
    addAccount: 'افزودن حساب',

    orders: 'سفارش‌ها',
    active: 'فعال',
    completed: 'تکمیل‌شده',
    myOffers: 'آگهی‌های من',
    noActive: 'معاملهٔ فعالی ندارید.',
    noCompleted: 'هنوز معامله‌ای تکمیل نشده.',
    noMyOffers: 'آگهی‌ای ندارید.',
    st_pending_payment: 'در انتظار پرداخت',
    st_pending_payment_buyer: 'در انتظار پرداخت شما',
    st_paid: 'پرداخت شد — منتظر فروشنده',
    st_paid_seller: 'خریدار پرداخت کرد — حساب خود را بررسی کنید',
    st_disputed: 'در حال داوری',
    st_completed: 'تکمیل شد',
    st_cancelled: 'لغو شد',
    offer_active: 'فعال',
    offer_paused: 'متوقف',
    offer_closed: 'بسته',
    pause: 'توقف',
    resume: 'فعال‌سازی',
    closeOffer: 'بستن آگهی',
    remaining: 'باقی‌مانده',

    profile: 'حساب من',
    verified: 'تأییدشده',
    completionRate: 'نرخ تکمیل',
    myPaymentAccounts: 'حساب‌های دریافت پول',
    noPaymentAccounts: 'هنوز حسابی ثبت نکرده‌اید.',
    holderName: 'نام صاحب حساب',
    accountOrPhone: 'شماره حساب یا موبایل',
    save: 'ذخیره',
    remove: 'حذف',
    appearance: 'حالت نمایش',
    dark: 'تیره',
    light: 'روشن',
    security: 'امنیت و تأیید دومرحله‌ای',
    soon: 'به‌زودی',
    support: 'پشتیبانی',
    logout: 'خروج از حساب',
    adminPanel: 'پنل مدیریت',

    home: 'خانه',

    err_network_error: 'اتصال برقرار نشد. اینترنت خود را بررسی کنید.',
    err_server_error: 'خطای سرور. کمی بعد دوباره تلاش کنید.',
    err_unauthorized: 'لطفاً وارد حساب شوید.',
    err_forbidden: 'اجازهٔ این کار را ندارید.',
    err_not_found: 'پیدا نشد.',
    err_too_many_requests: 'تلاش زیاد. چند دقیقه صبر کنید.',
    err_invalid_credentials: 'نام کاربری یا رمز عبور اشتباه است.',
    err_account_blocked: 'حساب شما مسدود شده است. با پشتیبانی تماس بگیرید.',
    err_invalid_username: 'نام کاربری باید ۳ تا ۲۴ حرف انگلیسی، عدد یا _ باشد.',
    err_weak_password: 'رمز عبور باید حداقل ۸ حرف باشد.',
    err_invalid_phone: 'شماره موبایل درست نیست.',
    err_username_taken: 'این نام کاربری گرفته شده است.',
    err_insufficient_balance: 'موجودی کافی نیست.',
    err_invalid_amount: 'مقدار درست نیست.',
    err_invalid_price: 'قیمت درست نیست.',
    err_invalid_limits: 'محدودهٔ معامله درست نیست.',
    err_invalid_payment_methods: 'حداقل یک روش پرداخت انتخاب کنید.',
    err_invalid_payment_method: 'روش پرداخت درست نیست.',
    err_invalid_payment_account: 'نام صاحب حساب و شماره را وارد کنید.',
    err_missing_payment_account: 'ابتدا حساب دریافت پول را برای این روش در «حساب من» ثبت کنید.',
    err_invalid_payment_window: 'مهلت پرداخت درست نیست.',
    err_offer_unavailable: 'این آگهی دیگر در دسترس نیست.',
    err_own_offer: 'نمی‌توانید با آگهی خودتان معامله کنید.',
    err_exceeds_available: 'مقدار بیشتر از موجودی آگهی است.',
    err_outside_limits: 'مبلغ خارج از محدودهٔ آگهی است.',
    err_too_many_open_trades: 'حداکثر ۵ معاملهٔ باز همزمان مجاز است.',
    err_invalid_state: 'وضعیت معامله تغییر کرده است. صفحه را تازه کنید.',
    err_reason_required: 'دلیل شکایت را بنویسید.',
    err_empty_message: 'پیام خالی است.',
    err_invalid_txid: 'شناسهٔ تراکنش درست نیست (۶۴ کاراکتر).',
    err_duplicate_txid: 'این تراکنش قبلاً ثبت شده است.',
    err_invalid_address: 'آدرس TRC20 درست نیست.',
    err_below_minimum: 'مقدار کمتر از حداقل برداشت است.',
    err_offer_closed: 'آگهی بسته شده است.',
  },

  en: {
    brandTagline: 'directly with Afghani',
    welcomeTitle: 'Buy and sell Tether,',
    welcomeSub: 'Peer-to-peer market with escrow — the seller’s USDT stays locked by the platform until your payment is confirmed.',
    createAccount: 'Create a free account',
    haveAccount: 'I have an account — log in',
    browseMarket: 'Browse the market without logging in',
    language: 'Language',

    welcomeBack: 'Welcome back',
    loginSub: 'Log in to buy and sell Tether.',
    registerTitle: 'Create account',
    registerSub: 'Choose a username and password.',
    login: 'Log in',
    register: 'Sign up',
    username: 'Username',
    usernameHint: '3–24 letters, digits or _',
    displayName: 'Display name',
    phone: 'Mobile number',
    password: 'Password',
    passwordHint: 'At least 8 characters',
    showPassword: 'Show password',
    secureNote: 'Encrypted connection and two-step confirmation for withdrawals',
    back: 'Back',
    close: 'Close',

    greeting: 'Hello',
    totalBalance: 'Total balance',
    hideBalance: 'Hide balance',
    available: 'Available',
    inEscrow: 'In escrow',
    approxAfn: '≈ {v} AFN',
    deposit: 'Deposit',
    withdraw: 'Withdraw',
    buy: 'Buy',
    sell: 'Sell',
    bestBuy: 'Best buy price',
    bestSell: 'Best sell price',
    goMarket: 'Go to market',
    activeTrades: 'Active trades',
    all: 'All',
    recentActivity: 'Recent activity',
    noActivity: 'No activity yet. Start by depositing USDT or buying from the market.',

    market: 'P2P market',
    marketSub: 'Trade directly with people',
    buyUsdt: 'Buy USDT',
    sellUsdt: 'Sell USDT',
    amountAfnFilter: 'Amount in AFN',
    filters: 'Filters',
    newOffer: 'New offer',
    trades: 'trades',
    completion: 'completion',
    perUsdt: 'per USDT',
    availableAmt: 'Available',
    limits: 'Limits',
    noOffers: 'No offers match right now.',
    postFirstOffer: 'Post the first offer',

    escrow: 'Escrow',
    memberTrades: 'Trades',
    payWindow: 'Payment window',
    minutes: '{n} min',
    youPay: 'You pay',
    youSell: 'You sell',
    youReceive: 'You receive',
    inAfn: 'AFN',
    max: 'Max',
    fee: 'Fee',
    paymentMethod: 'Payment method',
    sellerTerms: 'Advertiser terms',
    escrowNote: 'The seller’s USDT is locked in platform escrow until the trade ends.',
    buyAmount: 'Buy {v} USDT',
    sellAmount: 'Sell {v} USDT',
    loginToTrade: 'Log in to trade',
    needAccountFor: 'To sell, first add your {m} receiving account in Profile.',

    order: 'Order',
    buyFrom: 'Buy from {n}',
    sellTo: 'Sell to {n}',
    payNow: 'Please make the payment',
    payNowSub: 'If you don’t pay before the timer ends, the order is cancelled automatically.',
    waitBuyer: 'Waiting for the buyer to pay',
    waitBuyerSub: 'After the buyer pays, check your account and release the USDT.',
    waitSeller: 'Waiting for the seller',
    waitSellerSub: 'The seller is checking your payment and will release the USDT.',
    checkPayment: 'The buyer has paid',
    checkPaymentSub: 'Release the USDT only after you see the money in your account.',
    disputed: 'Under review',
    disputedSub: 'Support is reviewing both sides. The USDT stays locked until a decision.',
    stepPay: 'Pay',
    stepConfirm: 'Seller confirms',
    stepReceive: 'Receive',
    amountToPay: 'Amount to pay',
    amountToReceive: 'Amount you receive',
    copy: 'Copy',
    copied: 'Copied',
    price: 'Price',
    receiveNet: 'Buyer receives',
    recipientName: 'Recipient name',
    accountNumber: 'Account number',
    noAccountInfo: 'The seller hasn’t added account details yet — ask in chat.',
    payWarning: 'Only pay from an account in your own name and don’t write “USDT” in the payment note.',
    releaseWarning: 'Never release USDT before the money reaches your account. A receipt photo is not enough.',
    iPaid: 'I have paid',
    cancelOrder: 'Cancel order',
    confirmCancel: 'Cancel this order? Don’t cancel if you already sent money.',
    release: 'I got the money — release USDT',
    confirmRelease: 'Are you sure {v} AFN has arrived in your account? This cannot be undone.',
    openDispute: 'Open dispute',
    disputeReason: 'Reason',
    disputePlaceholder: 'What happened? e.g. I paid but the seller does not respond.',
    submit: 'Submit',
    cancel: 'Cancel',
    confirm: 'Confirm',
    chat: 'Chat',
    tradeDone: 'Trade completed',
    addedToWallet: 'Added to your wallet and ready to use.',
    soldDone: 'USDT sold and delivered to the buyer.',
    tradeCancelled: 'Order cancelled',
    tradeCancelledSub: 'The escrowed USDT went back to the seller.',
    orderNo: 'Order no.',
    counterparty: 'Counterparty',
    paid: 'Paid',
    viewWallet: 'View wallet',
    newTrade: 'New trade',

    online: 'Online',
    writeMessage: 'Write a message…',
    send: 'Send',
    chatSafety: 'Never send USDT outside the platform — support can see this chat.',
    noMessages: 'No messages yet. Say hello!',
    sys_trade_opened: 'Order created · seller’s USDT locked in escrow',
    sys_trade_marked_paid: 'Buyer marked as paid · waiting for seller',
    sys_trade_released: 'Seller released the USDT · trade completed',
    sys_trade_cancelled_by_buyer: 'Buyer cancelled the order',
    sys_trade_expired: 'Payment window ended · order cancelled',
    sys_trade_disputed: 'Dispute opened · support is reviewing',
    sys_trade_resolved_buyer: 'Resolved in favour of the buyer',
    sys_trade_resolved_seller: 'Resolved in favour of the seller',

    wallet: 'Wallet',
    network: 'Network',
    tether: 'Tether',
    history: 'History',
    today: 'Today',
    yesterday: 'Yesterday',
    kind_deposit: 'USDT deposit',
    kind_withdraw_lock: 'Withdrawal requested',
    kind_withdraw_refund: 'Withdrawal rejected · refunded',
    kind_withdrawal: 'Withdrawal sent',
    kind_offer_lock: 'Locked for sell offer',
    kind_offer_unlock: 'Offer unlocked',
    kind_trade_lock: 'Locked for trade',
    kind_trade_refund: 'Returned from trade',
    kind_escrow_release: 'Sold USDT',
    kind_trade_receive: 'Bought USDT',
    status_pending: 'Under review',
    status_approved: 'Approved',
    status_rejected: 'Rejected',
    status_sent: 'Sent',

    depositUsdt: 'Deposit USDT',
    tronNetwork: 'Tron network (TRC20)',
    onlyNetwork: 'The only supported network',
    depositAddress: 'Deposit address',
    depositWarning: 'Send only USDT on the TRC20 network. Sending from other networks such as ERC20 or BEP20 will lose the funds.',
    afterSending: 'After sending, enter the amount and transaction ID (TxID)',
    amount: 'Amount',
    txid: 'Transaction ID (TxID)',
    paste: 'Paste',
    submitDeposit: 'Submit deposit',
    depositSubmitted: 'Deposit submitted. It will be credited after on-chain review.',
    recentDeposits: 'Recent deposits',

    withdrawUsdt: 'Withdraw USDT',
    destAddress: 'Destination address',
    destHint: 'The address must start with T and be on the Tron network.',
    networkFee: 'Network fee',
    totalDeducted: 'Deducted from balance',
    destReceives: 'Destination receives',
    minWithdraw: 'Minimum withdrawal: {v} USDT',
    confirmWithdraw: 'Confirm withdrawal',
    withdrawNote: 'Withdrawals are sent on-chain after a security review.',
    withdrawSubmitted: 'Withdrawal requested.',
    recentWithdrawals: 'Recent withdrawals',

    createOffer: 'Create offer',
    iWantBuy: 'I want to buy',
    iWantSell: 'I want to sell',
    pricePerUsdt: 'Price per USDT',
    marketBest: 'Current best market price: {v} AFN',
    totalToSell: 'Total to sell',
    totalToBuy: 'Total to buy',
    perTradeLimits: 'Per-trade limits (AFN)',
    min: 'Min',
    receiveMethods: 'How you get paid',
    payMethods: 'How you pay',
    buyerWindow: 'Buyer payment window',
    terms: 'Terms (optional)',
    termsPlaceholder: 'e.g. Only pay from an account in your own name.',
    lockNote: '{v} USDT is locked in escrow until the offer is closed.',
    publishOffer: 'Publish offer',
    offerPublished: 'Offer published.',
    missingAccounts: 'You have no receiving account for: {m}',
    addAccount: 'Add account',

    orders: 'Orders',
    active: 'Active',
    completed: 'Completed',
    myOffers: 'My offers',
    noActive: 'No active trades.',
    noCompleted: 'No completed trades yet.',
    noMyOffers: 'You have no offers.',
    st_pending_payment: 'Waiting for payment',
    st_pending_payment_buyer: 'Waiting for your payment',
    st_paid: 'Paid — waiting for seller',
    st_paid_seller: 'Buyer paid — check your account',
    st_disputed: 'Under review',
    st_completed: 'Completed',
    st_cancelled: 'Cancelled',
    offer_active: 'Active',
    offer_paused: 'Paused',
    offer_closed: 'Closed',
    pause: 'Pause',
    resume: 'Resume',
    closeOffer: 'Close offer',
    remaining: 'Remaining',

    profile: 'Profile',
    verified: 'Verified',
    completionRate: 'Completion',
    myPaymentAccounts: 'Receiving accounts',
    noPaymentAccounts: 'No accounts added yet.',
    holderName: 'Account holder name',
    accountOrPhone: 'Account or mobile number',
    save: 'Save',
    remove: 'Remove',
    appearance: 'Appearance',
    dark: 'Dark',
    light: 'Light',
    security: 'Security & two-step verification',
    soon: 'Soon',
    support: 'Support',
    logout: 'Log out',
    adminPanel: 'Admin panel',

    home: 'Home',

    err_network_error: 'Could not connect. Check your internet.',
    err_server_error: 'Server error. Please try again shortly.',
    err_unauthorized: 'Please log in.',
    err_forbidden: 'You are not allowed to do this.',
    err_not_found: 'Not found.',
    err_too_many_requests: 'Too many attempts. Wait a few minutes.',
    err_invalid_credentials: 'Wrong username or password.',
    err_account_blocked: 'Your account is blocked. Contact support.',
    err_invalid_username: 'Username must be 3–24 letters, digits or _.',
    err_weak_password: 'Password must be at least 8 characters.',
    err_invalid_phone: 'Invalid mobile number.',
    err_username_taken: 'This username is taken.',
    err_insufficient_balance: 'Insufficient balance.',
    err_invalid_amount: 'Invalid amount.',
    err_invalid_price: 'Invalid price.',
    err_invalid_limits: 'Invalid trade limits.',
    err_invalid_payment_methods: 'Choose at least one payment method.',
    err_invalid_payment_method: 'Invalid payment method.',
    err_invalid_payment_account: 'Enter the holder name and number.',
    err_missing_payment_account: 'First add a receiving account for this method in Profile.',
    err_invalid_payment_window: 'Invalid payment window.',
    err_offer_unavailable: 'This offer is no longer available.',
    err_own_offer: 'You can’t trade with your own offer.',
    err_exceeds_available: 'Amount exceeds what the offer has left.',
    err_outside_limits: 'Amount is outside the offer limits.',
    err_too_many_open_trades: 'At most 5 open trades at a time.',
    err_invalid_state: 'The trade changed. Refresh the page.',
    err_reason_required: 'Describe the problem.',
    err_empty_message: 'Message is empty.',
    err_invalid_txid: 'Invalid transaction ID (64 characters).',
    err_duplicate_txid: 'This transaction was already submitted.',
    err_invalid_address: 'Invalid TRC20 address.',
    err_below_minimum: 'Below the minimum withdrawal.',
    err_offer_closed: 'The offer is closed.',
  },
}

export const paymentMethodLabels = {
  fa: { hesabpay: 'HesabPay', mpaisa: 'M-Paisa', mhawala: 'M-Hawala', bank: 'حساب بانکی', hawala: 'حواله', cash: 'نقدی حضوری' },
  en: { hesabpay: 'HesabPay', mpaisa: 'M-Paisa', mhawala: 'M-Hawala', bank: 'Bank account', hawala: 'Hawala', cash: 'Cash in person' },
}

// Admin panel strings.
Object.assign(strings.fa, {
  support: 'پشتیبانی',
  admin: 'مدیریت',
  backToApp: 'بازگشت به اپ',
  overview: 'نمای کلی',
  deposits: 'واریزها',
  withdrawals: 'برداشت‌ها',
  disputes: 'داوری‌ها',
  users: 'کاربران',
  auditLog: 'گزارش اقدامات',
  pendingDeposits: 'واریز در انتظار',
  pendingWithdrawals: 'برداشت در انتظار',
  openDisputes: 'معامله در داوری',
  openTrades: 'معامله باز',
  userCount: 'کاربر',
  userBalances: 'موجودی کل کاربران',
  feesEarned: 'کمیشن دریافتی',
  pending: 'در انتظار',
  approve: 'تأیید',
  reject: 'رد',
  note: 'یادداشت (اختیاری)',
  noteRequired: 'دلیل رد',
  viewOnChain: 'مشاهده در Tronscan',
  checkOnChain: 'پیش از تأیید، تراکنش را در Tronscan بررسی کنید: مقصد باید آدرس پلتفرم، توکن USDT و شبکه TRC20 باشد.',
  creditAmount: 'مقدار واریز (در صورت تفاوت اصلاح کنید)',
  approveDeposit: 'تأیید و افزودن به موجودی',
  rejectDeposit: 'رد واریز',
  approveWithdrawal: 'ثبت ارسال',
  rejectWithdrawal: 'رد و بازگشت به موجودی',
  sentTxid: 'شناسهٔ تراکنش ارسال‌شده (TxID)',
  sendFirst: 'ابتدا مبلغ را از کیف پول گرم پلتفرم به این آدرس بفرستید، سپس TxID را اینجا ثبت کنید.',
  nothingPending: 'موردی در انتظار نیست.',
  buyer: 'خریدار',
  seller: 'فروشنده',
  reason: 'دلیل',
  review: 'بررسی',
  resolveBuyer: 'به نفع خریدار — آزادسازی تتر',
  resolveSeller: 'به نفع فروشنده — بازگشت تتر',
  confirmResolveBuyer: 'تتر امانی به خریدار داده می‌شود. این کار قابل برگشت نیست.',
  confirmResolveSeller: 'تتر امانی به فروشنده برمی‌گردد. این کار قابل برگشت نیست.',
  decisionNote: 'توضیح تصمیم (برای هر دو طرف نمایش داده می‌شود)',
  messageAsSupport: 'پیام به‌عنوان پشتیبانی…',
  searchUsers: 'جستجوی نام کاربری، نام یا شماره',
  block: 'مسدود کردن',
  unblock: 'رفع مسدودی',
  blocked: 'مسدود',
  joined: 'عضویت',
  action_deposit_approve: 'تأیید واریز',
  action_deposit_reject: 'رد واریز',
  action_withdrawal_approve: 'ثبت ارسال برداشت',
  action_withdrawal_reject: 'رد برداشت',
  action_resolve_buyer: 'داوری به نفع خریدار',
  action_resolve_seller: 'داوری به نفع فروشنده',
  action_user_block: 'مسدود کردن کاربر',
  action_user_unblock: 'رفع مسدودی کاربر',
  err_own_request: 'نمی‌توانید درخواست یا معاملهٔ خودتان را بررسی کنید.',
  err_already_reviewed: 'این مورد قبلاً بررسی شده است.',
  err_cannot_block_self: 'نمی‌توانید خودتان را مسدود کنید.',
  err_cannot_block_admin: 'مدیر را نمی‌توان مسدود کرد.',
  err_invalid_winner: 'طرف برنده مشخص نیست.',
})

Object.assign(strings.en, {
  support: 'Support',
  admin: 'Admin',
  backToApp: 'Back to app',
  overview: 'Overview',
  deposits: 'Deposits',
  withdrawals: 'Withdrawals',
  disputes: 'Disputes',
  users: 'Users',
  auditLog: 'Audit log',
  pendingDeposits: 'Pending deposits',
  pendingWithdrawals: 'Pending withdrawals',
  openDisputes: 'Open disputes',
  openTrades: 'Open trades',
  userCount: 'Users',
  userBalances: 'Total user balances',
  feesEarned: 'Fees earned',
  pending: 'Pending',
  approve: 'Approve',
  reject: 'Reject',
  note: 'Note (optional)',
  noteRequired: 'Reason for rejection',
  viewOnChain: 'View on Tronscan',
  checkOnChain: 'Check the transaction on Tronscan first: it must go to the platform address, as USDT on TRC20.',
  creditAmount: 'Amount to credit (correct it if different)',
  approveDeposit: 'Approve and credit',
  rejectDeposit: 'Reject deposit',
  approveWithdrawal: 'Mark as sent',
  rejectWithdrawal: 'Reject and refund',
  sentTxid: 'Sent transaction ID (TxID)',
  sendFirst: 'First send the amount from the platform hot wallet to this address, then record the TxID here.',
  nothingPending: 'Nothing pending.',
  buyer: 'Buyer',
  seller: 'Seller',
  reason: 'Reason',
  review: 'Review',
  resolveBuyer: 'For the buyer — release USDT',
  resolveSeller: 'For the seller — return USDT',
  confirmResolveBuyer: 'The escrowed USDT goes to the buyer. This cannot be undone.',
  confirmResolveSeller: 'The escrowed USDT returns to the seller. This cannot be undone.',
  decisionNote: 'Decision note (shown to both parties)',
  messageAsSupport: 'Message as support…',
  searchUsers: 'Search username, name or phone',
  block: 'Block',
  unblock: 'Unblock',
  blocked: 'Blocked',
  joined: 'Joined',
  action_deposit_approve: 'Approved deposit',
  action_deposit_reject: 'Rejected deposit',
  action_withdrawal_approve: 'Marked withdrawal sent',
  action_withdrawal_reject: 'Rejected withdrawal',
  action_resolve_buyer: 'Resolved for buyer',
  action_resolve_seller: 'Resolved for seller',
  action_user_block: 'Blocked user',
  action_user_unblock: 'Unblocked user',
  err_own_request: 'You can’t review your own request or trade.',
  err_already_reviewed: 'Already reviewed.',
  err_cannot_block_self: 'You can’t block yourself.',
  err_cannot_block_admin: 'Admins can’t be blocked.',
  err_invalid_winner: 'Choose a side.',
})

// Chain mode strings.
Object.assign(strings.fa, {
  yourDepositAddress: 'آدرس واریز اختصاصی شما',
  personalAddressNote: 'این آدرس فقط مال شماست. هر مقدار USDT (TRC20) که به آن بفرستید، پس از تأیید شبکه (حدود ۱ دقیقه) خودکار به موجودی شما اضافه می‌شود.',
  minDeposit: 'حداقل واریز: {v} USDT — کمتر از این اضافه نمی‌شود.',
  checkNow: 'بررسی واریز جدید',
  checking: 'در حال بررسی…',
  newDepositsCredited: '{n} واریز جدید به موجودی اضافه شد.',
  noNewDeposits: 'واریز تأییدشدهٔ جدیدی پیدا نشد. اگر همین حالا فرستاده‌اید، یک دقیقه صبر کنید.',
  status_sending: 'در حال ارسال',
  status_failed: 'ناموفق — در دست بررسی',
  source_chain: 'خودکار',
  source_manual: 'دستی',
  chainStatus: 'کیف پول گرم (TRC20)',
  hotAddress: 'آدرس کیف پول گرم',
  coldAddress: 'کیف پول سرد',
  hotUsdt: 'موجودی USDT',
  hotTrx: 'موجودی TRX (کارمزد)',
  autoLimit: 'سقف ارسال خودکار',
  autoToday: 'ارسال خودکار امروز',
  awaitingSweep: 'آدرس در انتظار جمع‌آوری',
  inFlight: 'در حال ارسال / ناموفق',
  lastCheck: 'آخرین بررسی شبکه',
  chainError: 'خطای شبکه',
  sendFromHot: 'ارسال از کیف پول گرم',
  retrySend: 'ارسال دوباره',
  confirmSendHot: '{v} USDT از کیف پول گرم به این آدرس فرستاده می‌شود. این کار قابل برگشت نیست.',
  manualTxid: 'ثبت دستی TxID (ارسال از کیف پول دیگر)',
  attempts: 'تلاش',
  autoSent: 'خودکار',
  err_chain_deposits_only: 'واریز به آدرس اختصاصی شما خودکار ثبت می‌شود.',
  err_hot_wallet_low: 'موجودی USDT کیف پول گرم کافی نیست.',
  err_hot_wallet_no_trx: 'TRX کیف پول گرم برای کارمزد کافی نیست.',
  err_retry_later: 'تراکنش قبلی هنوز ممکن است ثبت شود. چند دقیقه دیگر دوباره تلاش کنید.',
  err_already_sent: 'این برداشت در واقع روی شبکه ثبت شده بود و اکنون «ارسال شد» است.',
  err_chain_off: 'حالت شبکه خاموش است.',
})

Object.assign(strings.en, {
  yourDepositAddress: 'Your personal deposit address',
  personalAddressNote: 'This address is yours alone. Any USDT (TRC20) sent to it is credited automatically after network confirmation (about 1 minute).',
  minDeposit: 'Minimum deposit: {v} USDT — smaller amounts are not credited.',
  checkNow: 'Check for new deposits',
  checking: 'Checking…',
  newDepositsCredited: '{n} new deposit(s) credited.',
  noNewDeposits: 'No new confirmed deposit yet. If you just sent it, wait a minute.',
  status_sending: 'Sending',
  status_failed: 'Failed — under review',
  source_chain: 'Automatic',
  source_manual: 'Manual',
  chainStatus: 'Hot wallet (TRC20)',
  hotAddress: 'Hot wallet address',
  coldAddress: 'Cold wallet',
  hotUsdt: 'USDT balance',
  hotTrx: 'TRX balance (fees)',
  autoLimit: 'Auto-send limit',
  autoToday: 'Auto-sent today',
  awaitingSweep: 'Addresses awaiting sweep',
  inFlight: 'Sending / failed',
  lastCheck: 'Last chain check',
  chainError: 'Chain error',
  sendFromHot: 'Send from hot wallet',
  retrySend: 'Retry send',
  confirmSendHot: '{v} USDT will be sent from the hot wallet to this address. This cannot be undone.',
  manualTxid: 'Record TxID manually (paid from another wallet)',
  attempts: 'attempts',
  autoSent: 'auto',
  err_chain_deposits_only: 'Deposits to your personal address are credited automatically.',
  err_hot_wallet_low: 'The hot wallet does not have enough USDT.',
  err_hot_wallet_no_trx: 'The hot wallet does not have enough TRX for fees.',
  err_retry_later: 'The previous transaction could still land. Try again in a few minutes.',
  err_already_sent: 'This withdrawal had actually landed on chain and is now marked sent.',
  err_chain_off: 'Chain mode is off.',
})

// Security & verification strings.
Object.assign(strings.fa, {
  twoFactorTitle: 'تأیید دومرحله‌ای',
  twoFactorSub: 'کد ۶ رقمی اپ احراز هویت (Google Authenticator و مانند آن) را وارد کنید. کد پشتیبان هم قبول است.',
  code: 'کد',
  verify: 'تأیید',
  securityTitle: 'امنیت حساب',
  phoneSection: 'شماره موبایل',
  phoneVerifiedAs: 'تأییدشده: {p}',
  phoneNotVerified: 'شماره موبایل خود را تأیید کنید تا بتوانید معامله و برداشت کنید.',
  sendCode: 'ارسال کد',
  resend: 'ارسال دوباره',
  codeSentTo: 'کد به {p} فرستاده شد.',
  authenticatorSection: 'اپ احراز هویت (2FA)',
  totpOn: 'فعال — برای ورود و برداشت کد اپ لازم است.',
  totpOff: 'غیرفعال. با فعال کردن آن، حساب شما حتی با لو رفتن رمز امن می‌ماند.',
  enableTotp: 'فعال‌سازی',
  disableTotp: 'غیرفعال کردن',
  scanQr: '۱. این QR را با اپ احراز هویت اسکن کنید (یا کلید را دستی وارد کنید).',
  enterAppCode: '۲. کد ۶ رقمی نمایش‌داده‌شده در اپ را وارد کنید.',
  backupCodesTitle: 'کدهای پشتیبان',
  backupCodesNote: 'این کدها را جای امنی یادداشت کنید. اگر گوشی را گم کنید، با هر کدام یک‌بار می‌توانید وارد شوید. دوباره نمایش داده نمی‌شوند.',
  backupLeft: '{n} کد پشتیبان باقی مانده',
  newBackupCodes: 'ساخت کدهای پشتیبان جدید',
  done: 'انجام شد',
  passwordSection: 'تغییر رمز عبور',
  currentPassword: 'رمز فعلی',
  newPassword: 'رمز جدید',
  passwordChanged: 'رمز تغییر کرد. نشست‌های دیگر بسته شدند.',
  recentSecurity: 'فعالیت‌های امنیتی اخیر',
  ev_login: 'ورود',
  ev_login_failed: 'ورود ناموفق',
  ev_registered: 'ثبت نام',
  ev_phone_verified: 'تأیید شماره',
  ev_totp_enabled: 'فعال شدن 2FA',
  ev_totp_disabled: 'غیرفعال شدن 2FA',
  ev_totp_failed: 'کد 2FA اشتباه',
  ev_password_changed: 'تغییر رمز',
  ev_password_change_failed: 'تغییر رمز ناموفق',
  ev_withdrawal_requested: 'درخواست برداشت',
  ev_code_sent_phone: 'ارسال کد تأیید شماره',
  ev_code_sent_withdraw: 'ارسال کد برداشت',
  ev_code_failed_phone: 'کد شماره اشتباه',
  ev_code_failed_withdraw: 'کد برداشت اشتباه',
  verificationTitle: 'احراز هویت',
  tier: 'سطح {n}',
  tierName0: 'پایه',
  tierName1: 'تأیید شماره',
  tierName2: 'تأیید هویت',
  tierName3: 'تاجر',
  tierReq0: 'فقط واریز',
  tierReq1: 'تأیید شمارهٔ موبایل با کد پیامکی',
  tierReq2: 'تذکره یا پاسپورت + عکس سلفی',
  tierReq3: 'با درخواست از پشتیبانی',
  dailyTrade: 'سقف معاملهٔ روزانه',
  dailyWithdraw: 'سقف برداشت روزانه',
  usedToday: '{u} از {l} USDT در ۲۴ ساعت گذشته',
  verifyPhoneCta: 'تأیید شمارهٔ موبایل',
  identitySection: 'مدارک هویتی',
  docType: 'نوع مدرک',
  tazkira: 'تذکره',
  passport: 'پاسپورت',
  fullName: 'نام کامل (مطابق مدرک)',
  docNumber: 'شمارهٔ مدرک',
  frontPhoto: 'عکس روی مدرک',
  backPhoto: 'عکس پشت مدرک (اختیاری)',
  selfiePhoto: 'سلفی با مدرک در دست',
  choosePhoto: 'انتخاب یا گرفتن عکس',
  uploaded: 'بارگذاری شد',
  submitForReview: 'ارسال برای بررسی',
  kycPendingNote: 'مدارک شما در حال بررسی است. معمولاً کمتر از ۲۴ ساعت طول می‌کشد.',
  kycRejectedNote: 'مدارک قبلی رد شد: {r} — لطفاً دوباره ارسال کنید.',
  kycApprovedNote: 'هویت شما تأیید شد.',
  kycPrivacy: 'مدارک به‌صورت رمزگذاری‌شده نگهداری می‌شوند و فقط کارشناس احراز هویت آن‌ها را می‌بیند.',
  verifyToTrade: 'برای شروع معامله، شمارهٔ موبایل خود را تأیید کنید.',
  goVerify: 'احراز هویت',
  securityCode: 'کد امنیتی',
  authenticatorCode: 'کد اپ احراز هویت',
  smsCode: 'کد پیامکی',
  withdrawNeedsVerify: 'برای برداشت ابتدا شمارهٔ موبایل خود را تأیید کنید.',
  remainingToday: 'باقی‌ماندهٔ سقف امروز: {v} USDT',
  staffNeeds2fa: 'برای استفاده از پنل مدیریت، ابتدا اپ احراز هویت (2FA) را در «امنیت حساب» فعال کنید.',
  kyc: 'احراز هویت',
  alerts: 'هشدارها',
  approveTier2: 'تأیید — سطح ۲',
  approveTier3: 'تأیید — سطح ۳ (تاجر)',
  rejectReason: 'دلیل رد (به کاربر نمایش داده می‌شود)',
  closeAlert: 'بستن هشدار',
  alertNote: 'نتیجهٔ بررسی',
  rule_pass_through: 'عبور سریع پول (واریز و برداشت بدون معامله)',
  rule_shared_address: 'آدرس برداشت مشترک با حساب دیگر',
  rule_large_trade: 'معاملهٔ بزرگ',
  rule_many_cancels: 'لغو زیاد',
  rule_many_disputes: 'شکایت زیاد',
  rule_auth_failures: 'تلاش‌های ناموفق امنیتی',
  severity_info: 'اطلاع',
  severity_low: 'کم',
  severity_medium: 'متوسط',
  severity_high: 'زیاد',
  role: 'نقش',
  role_user: 'کاربر',
  role_admin: 'مدیر کل',
  role_finance: 'مالی',
  role_support: 'پشتیبان',
  setRole: 'تغییر نقش',
  setTier: 'تغییر سطح',
  action_kyc_approve: 'تأیید احراز هویت',
  action_kyc_reject: 'رد احراز هویت',
  action_alert_close: 'بستن هشدار',
  action_role_user: 'نقش: کاربر',
  action_role_admin: 'نقش: مدیر کل',
  action_role_finance: 'نقش: مالی',
  action_role_support: 'نقش: پشتیبان',
  action_tier_0: 'سطح ۰',
  action_tier_1: 'سطح ۱',
  action_tier_2: 'سطح ۲',
  action_tier_3: 'سطح ۳',
  action_withdrawal_send: 'ارسال برداشت از کیف پول گرم',
  err_code_recently_sent: 'کد همین حالا فرستاده شد. یک دقیقه صبر کنید.',
  err_code_expired: 'کد منقضی شده یا وجود ندارد. کد جدید بگیرید.',
  err_invalid_code: 'کد اشتباه است.',
  err_phone_in_use: 'این شماره قبلاً برای حساب دیگری تأیید شده است.',
  err_verification_required: 'ابتدا شمارهٔ موبایل خود را تأیید کنید.',
  err_use_authenticator: 'از کد اپ احراز هویت استفاده کنید.',
  err_kyc_required: 'برای این کار باید احراز هویت کنید.',
  err_limit_exceeded: 'از سقف روزانهٔ سطح شما بیشتر است. سطح احراز هویت را بالا ببرید.',
  err_counterparty_limit: 'طرف مقابل به سقف معاملهٔ خود رسیده است.',
  err_phone_first: 'ابتدا شمارهٔ موبایل خود را تأیید کنید.',
  err_kyc_pending: 'مدارک شما در حال بررسی است.',
  err_invalid_doc_type: 'نوع مدرک را انتخاب کنید.',
  err_invalid_full_name: 'نام کامل را وارد کنید.',
  err_invalid_doc_number: 'شمارهٔ مدرک درست نیست.',
  err_invalid_image: 'فایل باید عکس JPG، PNG یا WebP باشد.',
  err_file_too_large: 'عکس بزرگ‌تر از ۵ مگابایت است.',
  err_empty_file: 'فایل خالی است.',
  err_kyc_files_missing: 'عکس روی مدرک و سلفی لازم است.',
  err_kyc_not_editable: 'این درخواست دیگر قابل ویرایش نیست.',
  err_account_locked: 'به دلیل تلاش‌های ناموفق، حساب ۱۵ دقیقه قفل شد.',
  err_challenge_expired: 'زمان ورود تمام شد. دوباره وارد شوید.',
  err_invalid_password: 'رمز فعلی اشتباه است.',
  err_totp_already_enabled: '2FA قبلاً فعال شده است.',
  err_totp_not_started: 'ابتدا «فعال‌سازی» را بزنید.',
  err_totp_not_enabled: '2FA فعال نیست.',
  err_staff_2fa_required: 'کارکنان باید 2FA را فعال نگه دارند.',
  err_invalid_role: 'نقش درست نیست.',
  err_invalid_tier: 'سطح درست نیست.',
})

Object.assign(strings.en, {
  twoFactorTitle: 'Two-step verification',
  twoFactorSub: 'Enter the 6-digit code from your authenticator app (Google Authenticator etc.). A backup code also works.',
  code: 'Code',
  verify: 'Verify',
  securityTitle: 'Account security',
  phoneSection: 'Mobile number',
  phoneVerifiedAs: 'Verified: {p}',
  phoneNotVerified: 'Verify your mobile number to trade and withdraw.',
  sendCode: 'Send code',
  resend: 'Resend',
  codeSentTo: 'Code sent to {p}.',
  authenticatorSection: 'Authenticator app (2FA)',
  totpOn: 'On — an app code is needed to log in and withdraw.',
  totpOff: 'Off. Turn it on so your account stays safe even if your password leaks.',
  enableTotp: 'Turn on',
  disableTotp: 'Turn off',
  scanQr: '1. Scan this QR with your authenticator app (or enter the key by hand).',
  enterAppCode: '2. Enter the 6-digit code the app shows.',
  backupCodesTitle: 'Backup codes',
  backupCodesNote: 'Write these down somewhere safe. If you lose your phone, each one logs you in once. They will not be shown again.',
  backupLeft: '{n} backup codes left',
  newBackupCodes: 'New backup codes',
  done: 'Done',
  passwordSection: 'Change password',
  currentPassword: 'Current password',
  newPassword: 'New password',
  passwordChanged: 'Password changed. Other sessions were signed out.',
  recentSecurity: 'Recent security activity',
  ev_login: 'Login',
  ev_login_failed: 'Failed login',
  ev_registered: 'Signed up',
  ev_phone_verified: 'Phone verified',
  ev_totp_enabled: '2FA turned on',
  ev_totp_disabled: '2FA turned off',
  ev_totp_failed: 'Wrong 2FA code',
  ev_password_changed: 'Password changed',
  ev_password_change_failed: 'Password change failed',
  ev_withdrawal_requested: 'Withdrawal requested',
  ev_code_sent_phone: 'Phone code sent',
  ev_code_sent_withdraw: 'Withdrawal code sent',
  ev_code_failed_phone: 'Wrong phone code',
  ev_code_failed_withdraw: 'Wrong withdrawal code',
  verificationTitle: 'Verification',
  tier: 'Level {n}',
  tierName0: 'Basic',
  tierName1: 'Phone verified',
  tierName2: 'Identity verified',
  tierName3: 'Merchant',
  tierReq0: 'Deposits only',
  tierReq1: 'Verify your mobile number by SMS',
  tierReq2: 'Tazkira or passport + selfie',
  tierReq3: 'On request to support',
  dailyTrade: 'Daily trade limit',
  dailyWithdraw: 'Daily withdrawal limit',
  usedToday: '{u} of {l} USDT in the last 24h',
  verifyPhoneCta: 'Verify mobile number',
  identitySection: 'Identity documents',
  docType: 'Document type',
  tazkira: 'Tazkira',
  passport: 'Passport',
  fullName: 'Full name (as on the document)',
  docNumber: 'Document number',
  frontPhoto: 'Front of the document',
  backPhoto: 'Back of the document (optional)',
  selfiePhoto: 'Selfie holding the document',
  choosePhoto: 'Choose or take a photo',
  uploaded: 'Uploaded',
  submitForReview: 'Submit for review',
  kycPendingNote: 'Your documents are being reviewed. This usually takes less than 24 hours.',
  kycRejectedNote: 'Your previous documents were rejected: {r} — please submit again.',
  kycApprovedNote: 'Your identity is verified.',
  kycPrivacy: 'Documents are stored encrypted and only the verification team can see them.',
  verifyToTrade: 'Verify your mobile number to start trading.',
  goVerify: 'Verify',
  securityCode: 'Security code',
  authenticatorCode: 'Authenticator code',
  smsCode: 'SMS code',
  withdrawNeedsVerify: 'Verify your mobile number before withdrawing.',
  remainingToday: 'Left of today’s limit: {v} USDT',
  staffNeeds2fa: 'To use the admin panel, first turn on the authenticator app (2FA) in Account security.',
  kyc: 'Verification',
  alerts: 'Alerts',
  approveTier2: 'Approve — level 2',
  approveTier3: 'Approve — level 3 (merchant)',
  rejectReason: 'Reason (shown to the user)',
  closeAlert: 'Close alert',
  alertNote: 'Outcome of review',
  rule_pass_through: 'Pass-through (deposit and withdraw without trading)',
  rule_shared_address: 'Withdrawal address shared with another account',
  rule_large_trade: 'Large trade',
  rule_many_cancels: 'Many cancellations',
  rule_many_disputes: 'Many disputes',
  rule_auth_failures: 'Repeated security failures',
  severity_info: 'Info',
  severity_low: 'Low',
  severity_medium: 'Medium',
  severity_high: 'High',
  role: 'Role',
  role_user: 'User',
  role_admin: 'Admin',
  role_finance: 'Finance',
  role_support: 'Support',
  setRole: 'Change role',
  setTier: 'Change level',
  action_kyc_approve: 'Approved verification',
  action_kyc_reject: 'Rejected verification',
  action_alert_close: 'Closed alert',
  action_role_user: 'Role: user',
  action_role_admin: 'Role: admin',
  action_role_finance: 'Role: finance',
  action_role_support: 'Role: support',
  action_tier_0: 'Level 0',
  action_tier_1: 'Level 1',
  action_tier_2: 'Level 2',
  action_tier_3: 'Level 3',
  action_withdrawal_send: 'Sent withdrawal from hot wallet',
  err_code_recently_sent: 'A code was just sent. Wait a minute.',
  err_code_expired: 'The code expired or does not exist. Get a new one.',
  err_invalid_code: 'Wrong code.',
  err_phone_in_use: 'This number is already verified on another account.',
  err_verification_required: 'Verify your mobile number first.',
  err_use_authenticator: 'Use your authenticator app code.',
  err_kyc_required: 'You need to verify your account for this.',
  err_limit_exceeded: 'This exceeds your daily limit. Raise your verification level.',
  err_counterparty_limit: 'The other party has reached their trade limit.',
  err_phone_first: 'Verify your mobile number first.',
  err_kyc_pending: 'Your documents are under review.',
  err_invalid_doc_type: 'Choose a document type.',
  err_invalid_full_name: 'Enter your full name.',
  err_invalid_doc_number: 'Invalid document number.',
  err_invalid_image: 'The file must be a JPG, PNG or WebP photo.',
  err_file_too_large: 'The photo is larger than 5 MB.',
  err_empty_file: 'Empty file.',
  err_kyc_files_missing: 'The front photo and a selfie are required.',
  err_kyc_not_editable: 'This request can no longer be edited.',
  err_account_locked: 'Too many failed attempts; the account is locked for 15 minutes.',
  err_challenge_expired: 'The login timed out. Log in again.',
  err_invalid_password: 'Current password is wrong.',
  err_totp_already_enabled: '2FA is already on.',
  err_totp_not_started: 'Press “Turn on” first.',
  err_totp_not_enabled: '2FA is not on.',
  err_staff_2fa_required: 'Staff must keep 2FA on.',
  err_invalid_role: 'Invalid role.',
  err_invalid_tier: 'Invalid level.',
})

// Closed beta strings: invites, beta caps, feedback, crash screen, admin Beta page.
Object.assign(strings.fa, {
  beta: 'بتا',
  betaBadge: 'بتا',
  betaNote: 'نسخهٔ آزمایشی — با مبلغ کم امتحان کنید',
  betaCap: 'سقف هر معامله {max} تتر',
  betaOfferCap: 'سقف هر آگهی {max} تتر',
  betaNoCap: 'بدون سقف معامله',
  betaInviteOnlyOn: 'ثبت‌نام فقط با کد دعوت',
  betaInviteOnlyOff: 'ثبت‌نام آزاد',
  sendFeedbackShort: 'نظر بدهید',
  betaTab_stats: 'آمار',
  betaTab_invites: 'دعوت‌ها',
  betaTab_feedback: 'بازخورد',
  betaTab_errors: 'خطاها',
  inviteCode: 'کد دعوت',
  inviteHint: 'در دورهٔ آزمایشی، ثبت‌نام فقط با کد دعوت ممکن است.',
  feedbackTitle: 'بازخورد و گزارش مشکل',
  feedbackSub: 'هر چیزی که کار نکرد، گیج‌کننده بود یا دوست دارید تغییر کند را بنویسید. تیم ما همه را می‌خواند و جواب می‌دهد.',
  feedbackKind: 'نوع بازخورد',
  feedbackMessage: 'توضیح',
  feedbackPrivacy: 'رمز عبور، کد تأیید یا کلمات بازیابی را هرگز اینجا ننویسید.',
  feedbackThanks: 'ممنون! پیام شما رسید.',
  sendFeedback: 'ارسال',
  myFeedback: 'پیام‌های من',
  noFeedbackYet: 'هنوز پیامی نفرستاده‌اید.',
  teamReply: 'پاسخ تیم',
  fb_bug: 'مشکل',
  fb_idea: 'پیشنهاد',
  fb_question: 'سؤال',
  fb_other: 'سایر',
  fbHint_bug: 'چه کاری می‌کردید؟ چه انتظاری داشتید و چه اتفاقی افتاد؟',
  fbHint_idea: 'چه چیزی کار شما را آسان‌تر می‌کند؟',
  fbHint_question: 'سؤال خود را بنویسید.',
  fbHint_other: 'پیام خود را بنویسید.',
  fbStatus_new: 'جدید',
  fbStatus_seen: 'دیده شد',
  fbStatus_done: 'انجام شد',
  crashTitle: 'مشکلی پیش آمد',
  crashSub: 'این صفحه با خطا روبه‌رو شد و گزارش آن خودکار برای تیم فرستاده شد. پول و معاملات شما دست‌نخورده است.',
  reload: 'بارگذاری دوباره',
  reportProblem: 'توضیح بیشتر برای تیم',
  bsUsers: 'کاربران',
  bsNew7d: '{n} نفر در ۷ روز اخیر',
  bsVerified: 'تأیید موبایل / مدرک',
  bsVerifiedSub: 'سطح ۱ / سطح ۲',
  bsActive: 'معامله‌گران فعال',
  bsLast7d: '۷ روز اخیر',
  bsCompleted: 'معاملهٔ تکمیل‌شده',
  bsOfTotal: 'از {n}',
  bsCancelled: '{n} لغو شده',
  bsDisputeRate: 'نرخ شکایت',
  bsDisputes: '{n} معامله',
  bsVolume: 'حجم معاملات',
  bsMedian: 'میانهٔ زمان معامله',
  bsMedianSub: 'از باز شدن تا آزادسازی',
  bsInvites: 'دعوت استفاده‌شده',
  bsInvitesSub: 'از ظرفیت کدهای فعال',
  bsFeedback: 'بازخورد جدید',
  bsErrors: 'خطای باز',
  bsEvents: '{n} بار رخ داده',
  minutesShort: '{n} دقیقه',
  chartSignups: 'ثبت‌نام روزانه',
  chartCompleted: 'معاملهٔ تکمیل‌شدهٔ روزانه',
  unitPeople: 'نفر',
  unitTrades: 'معامله',
  showTable: 'نمایش جدول',
  date: 'تاریخ',
  newInvite: 'کد دعوت جدید',
  inviteLabel: 'برای چه کسی؟',
  inviteLabelHint: 'مثلاً «گروه آزمایشی کابل»',
  inviteMaxUses: 'تعداد استفاده',
  inviteDays: 'اعتبار (روز)',
  createInvite: 'ساخت کد',
  inviteCreated: 'کد دعوت ساخته شد',
  inviteShownOnce: 'این کد فقط همین یک بار نمایش داده می‌شود. آن را کپی کنید یا لینک را بفرستید.',
  copyLink: 'کپی لینک',
  noInvites: 'هنوز کد دعوتی نساخته‌اید.',
  inviteUses: 'استفاده',
  inviteExpires: 'انقضا',
  inviteRevoked: 'باطل شده',
  inviteUsedUp: 'تمام شده',
  revoke: 'باطل کردن',
  markSeen: 'دیده شد',
  replyToUser: 'پاسخ به کاربر',
  reply: 'پاسخ',
  replyVisible: 'این پاسخ در صفحهٔ بازخورد کاربر نمایش داده می‌شود.',
  sendReplyDone: 'ارسال پاسخ و بستن',
  errorsOpen: 'باز',
  noErrors: 'خطایی گزارش نشده است.',
  errSource_web: 'مرورگر',
  errSource_server: 'سرور',
  lastSeen: 'آخرین بار',
  firstSeen: 'اولین بار',
  stackTrace: 'جزئیات فنی',
  markResolved: 'رفع شد',
  err_invite_required: 'برای ثبت‌نام در دورهٔ آزمایشی، کد دعوت لازم است.',
  err_invalid_invite: 'کد دعوت درست نیست، تمام شده یا منقضی شده است.',
  err_beta_trade_limit: 'در دورهٔ آزمایشی سقف هر معامله {max} تتر است.',
  err_beta_offer_limit: 'در دورهٔ آزمایشی سقف هر آگهی {max} تتر است.',
  err_invalid_feedback: 'نوع بازخورد را انتخاب کنید و حداقل چند کلمه بنویسید.',
  err_conflict: 'این کار هم‌زمان با تغییر دیگری انجام شد. صفحه را تازه کنید و دوباره امتحان کنید.',
  err_try_again: 'سرور مشغول بود. لطفاً دوباره امتحان کنید.',
  err_invalid_action: 'این کار در این مرحله ممکن نیست.',
  err_invalid_file_kind: 'نوع فایل درست نیست.',
  err_invalid_json: 'درخواست نامعتبر است. صفحه را تازه کنید.',
  err_json_required: 'درخواست نامعتبر است. صفحه را تازه کنید.',
  err_invalid_side: 'نوع آگهی (خرید یا فروش) را انتخاب کنید.',
  err_invalid_status: 'وضعیت انتخاب‌شده درست نیست.',
})
Object.assign(strings.en, {
  beta: 'Beta',
  betaBadge: 'Beta',
  betaNote: 'Test version — try it with small amounts',
  betaCap: 'max {max} USDT per trade',
  betaOfferCap: 'max {max} USDT per offer',
  betaNoCap: 'no trade cap',
  betaInviteOnlyOn: 'Sign-up by invite only',
  betaInviteOnlyOff: 'Open sign-up',
  sendFeedbackShort: 'Feedback',
  betaTab_stats: 'Stats',
  betaTab_invites: 'Invites',
  betaTab_feedback: 'Feedback',
  betaTab_errors: 'Errors',
  inviteCode: 'Invite code',
  inviteHint: 'During the beta you need an invite code to sign up.',
  feedbackTitle: 'Feedback & problems',
  feedbackSub: 'Tell us anything that broke, confused you or that you would change. The team reads every message and replies.',
  feedbackKind: 'Feedback type',
  feedbackMessage: 'Details',
  feedbackPrivacy: 'Never write passwords, verification codes or recovery words here.',
  feedbackThanks: 'Thank you! We got your message.',
  sendFeedback: 'Send',
  myFeedback: 'My messages',
  noFeedbackYet: 'You have not sent anything yet.',
  teamReply: 'Team reply',
  fb_bug: 'Problem',
  fb_idea: 'Idea',
  fb_question: 'Question',
  fb_other: 'Other',
  fbHint_bug: 'What were you doing? What did you expect, and what happened?',
  fbHint_idea: 'What would make this easier for you?',
  fbHint_question: 'Write your question.',
  fbHint_other: 'Write your message.',
  fbStatus_new: 'New',
  fbStatus_seen: 'Seen',
  fbStatus_done: 'Done',
  crashTitle: 'Something went wrong',
  crashSub: 'This page hit an error and a report was sent to the team automatically. Your money and trades are not affected.',
  reload: 'Reload',
  reportProblem: 'Tell the team more',
  bsUsers: 'Users',
  bsNew7d: '{n} in the last 7 days',
  bsVerified: 'Phone / ID verified',
  bsVerifiedSub: 'tier 1 / tier 2',
  bsActive: 'Active traders',
  bsLast7d: 'last 7 days',
  bsCompleted: 'Completed trades',
  bsOfTotal: 'of {n}',
  bsCancelled: '{n} cancelled',
  bsDisputeRate: 'Dispute rate',
  bsDisputes: '{n} trades',
  bsVolume: 'Trade volume',
  bsMedian: 'Median trade time',
  bsMedianSub: 'open to release',
  bsInvites: 'Invites used',
  bsInvitesSub: 'of active code capacity',
  bsFeedback: 'New feedback',
  bsErrors: 'Open errors',
  bsEvents: '{n} occurrences',
  minutesShort: '{n} min',
  chartSignups: 'Daily sign-ups',
  chartCompleted: 'Daily completed trades',
  unitPeople: 'people',
  unitTrades: 'trades',
  showTable: 'Show table',
  date: 'Date',
  newInvite: 'New invite code',
  inviteLabel: 'Who is it for?',
  inviteLabelHint: 'e.g. “Kabul test group”',
  inviteMaxUses: 'Uses',
  inviteDays: 'Valid (days)',
  createInvite: 'Create code',
  inviteCreated: 'Invite code created',
  inviteShownOnce: 'This code is shown only once. Copy it or send the link.',
  copyLink: 'Copy link',
  noInvites: 'No invite codes yet.',
  inviteUses: 'Used',
  inviteExpires: 'Expires',
  inviteRevoked: 'Revoked',
  inviteUsedUp: 'Used up',
  revoke: 'Revoke',
  markSeen: 'Mark seen',
  replyToUser: 'Reply to user',
  reply: 'Reply',
  replyVisible: 'The user sees this reply on their feedback page.',
  sendReplyDone: 'Send reply and close',
  errorsOpen: 'Open',
  noErrors: 'No errors reported.',
  errSource_web: 'Browser',
  errSource_server: 'Server',
  lastSeen: 'Last seen',
  firstSeen: 'First seen',
  stackTrace: 'Technical details',
  markResolved: 'Resolved',
  err_invite_required: 'You need an invite code to sign up during the beta.',
  err_invalid_invite: 'This invite code is wrong, used up or expired.',
  err_beta_trade_limit: 'During the beta each trade is limited to {max} USDT.',
  err_beta_offer_limit: 'During the beta each offer is limited to {max} USDT.',
  err_invalid_feedback: 'Choose a type and write at least a few words.',
  err_conflict: 'This happened at the same time as another change. Refresh and try again.',
  err_try_again: 'The server was busy. Please try again.',
  err_invalid_action: 'That is not possible at this step.',
  err_invalid_file_kind: 'Wrong file type.',
  err_invalid_json: 'Invalid request. Refresh the page.',
  err_json_required: 'Invalid request. Refresh the page.',
  err_invalid_side: 'Choose buy or sell.',
  err_invalid_status: 'Invalid status.',
})

// Release: terms, privacy, help, support, installing the app.
Object.assign(strings.fa, {
  termsTitle: 'قوانین استفاده',
  privacyTitle: 'حریم خصوصی',
  termsVersionLabel: 'نسخهٔ {v}',
  acceptTermsA: 'با',
  and: 'و',
  acceptTermsB: 'موافقم و حداقل ۱۸ سال دارم.',
  acceptAndClose: 'خواندم و موافقم',
  termsUpdated: 'قوانین استفاده و حریم خصوصی به‌روز شده است. لطفاً بخوانید و بپذیرید.',
  readTerms: 'خواندن',
  acceptTermsButton: 'موافقم',
  helpTitle: 'راهنما و پرسش‌های رایج',
  helpSub: 'پاسخ کوتاه به پرسش‌هایی که بیشتر از همه می‌پرسند.',
  stillNeedHelp: 'جوابتان را پیدا نکردید؟ پشتیبانی',
  supportTitle: 'پشتیبانی',
  supportSub: 'تیم پشتیبانی به پیام‌ها، شکایت‌های معاملات و مشکلات حساب رسیدگی می‌کند.',
  supportMessage: 'پیام به پشتیبانی در اپ',
  supportTradeHint: 'اگر مشکل مربوط به یک معامله است، در همان معامله «شکایت» باز کنید؛ پشتیبانی گفتگو و مدارک را همان‌جا می‌بیند.',
  supportPhone: 'تلفن / واتس‌اپ',
  supportEmail: 'ایمیل',
  supportHours: 'ساعات پاسخگویی',
  supportSafety: 'کارکنان P2PPay هرگز رمز عبور، کد تأیید یا کدهای پشتیبان شما را نمی‌خواهند و هرگز نمی‌گویند بیرون از اپ پول یا تتر بفرستید.',
  installApp: 'نصب روی گوشی',
  iosStep1: 'این صفحه را در Safari باز کنید.',
  iosStep2: 'دکمهٔ اشتراک‌گذاری (مربع با فلش رو به بالا) را بزنید.',
  iosStep3: '«Add to Home Screen» را انتخاب کنید.',
  err_terms_required: 'برای ساخت حساب، قوانین استفاده و حریم خصوصی را بپذیرید.',
  err_terms_outdated: 'قوانین دوباره تغییر کرده است. صفحه را تازه کنید.',
  offlineNote: 'اتصال اینترنت قطع است. وقتی وصل شوید، ادامه می‌دهیم.',
})
Object.assign(strings.en, {
  termsTitle: 'Terms of use',
  privacyTitle: 'Privacy',
  termsVersionLabel: 'Version {v}',
  acceptTermsA: 'I agree to the',
  and: 'and',
  acceptTermsB: 'and I am at least 18 years old.',
  acceptAndClose: 'I have read it and agree',
  termsUpdated: 'The terms of use and privacy notice have changed. Please read and accept them.',
  readTerms: 'Read',
  acceptTermsButton: 'I agree',
  helpTitle: 'Help & FAQ',
  helpSub: 'Short answers to the questions people ask most.',
  stillNeedHelp: 'Did not find your answer? Support',
  supportTitle: 'Support',
  supportSub: 'The support team answers messages, trade disputes and account problems.',
  supportMessage: 'Message support in the app',
  supportTradeHint: 'If the problem is about a trade, open a dispute in that trade; support sees the chat and evidence there.',
  supportPhone: 'Phone / WhatsApp',
  supportEmail: 'Email',
  supportHours: 'Support hours',
  supportSafety: 'P2PPay staff will never ask for your password, verification codes or backup codes, and will never tell you to send money or USDT outside the app.',
  installApp: 'Install on phone',
  iosStep1: 'Open this page in Safari.',
  iosStep2: 'Tap the Share button (a square with an arrow).',
  iosStep3: 'Choose “Add to Home Screen”.',
  err_terms_required: 'Accept the terms of use and privacy notice to create an account.',
  err_terms_outdated: 'The terms changed again. Refresh the page.',
  offlineNote: 'You are offline. We will continue when you are back online.',
})

// Notifications, ratings, trader profiles.
Object.assign(strings.fa, {
  notificationsTitle: 'اعلان‌ها',
  markAllRead: 'همه خوانده شد',
  noNotifications: 'اعلانی ندارید. وقتی معامله‌ای باز شود، پولی برسد یا پیامی بیاید، اینجا می‌بینید.',
  unread: 'خوانده‌نشده',
  pushTitle: 'اعلان روی گوشی',
  pushSub: 'وقتی خریدار پرداخت کرد یا تتر آزاد شد، حتی اگر اپ بسته باشد باخبر شوید.',
  pushOn: 'روشن است. مهم‌ترین رویدادها روی گوشی شما نمایش داده می‌شود.',
  pushDenied: 'اجازهٔ اعلان در تنظیمات مرورگر بسته شده است.',
  pushEnable: 'روشن کردن',
  pushDisable: 'خاموش کردن',
  ntf_trade_opened: 'معاملهٔ جدید روی آگهی شما',
  ntfsub_trade_opened: '{amount} تتر · معاملهٔ #{tradeId}',
  ntf_trade_paid: 'خریدار پرداخت کرد',
  ntfsub_trade_paid: 'پول را بررسی و تتر را آزاد کنید · #{tradeId}',
  ntf_trade_released: 'تتر آزاد شد',
  ntfsub_trade_released: '{amount} تتر به کیف پول شما آمد · #{tradeId}',
  ntf_trade_cancelled: 'معامله لغو شد',
  ntfsub_trade_cancelled: 'معاملهٔ #{tradeId}',
  ntf_trade_disputed: 'شکایت باز شد',
  ntfsub_trade_disputed: 'پشتیبانی بررسی می‌کند · #{tradeId}',
  ntf_trade_resolved: 'داوری انجام شد',
  ntfsub_trade_resolved: 'نتیجه را ببینید · #{tradeId}',
  ntf_trade_message: 'پیام جدید',
  ntfsub_trade_message: 'در معاملهٔ #{tradeId}',
  ntf_deposit_credited: 'واریز انجام شد',
  ntfsub_deposit_credited: '{amount} تتر',
  ntf_deposit_rejected: 'واریز تأیید نشد',
  ntfsub_deposit_rejected: '{amount} تتر',
  ntf_withdrawal_sent: 'برداشت ارسال شد',
  ntfsub_withdrawal_sent: '{amount} تتر',
  ntf_withdrawal_rejected: 'برداشت انجام نشد',
  ntfsub_withdrawal_rejected: 'موجودی به کیف پول برگشت',
  ntf_kyc_approved: 'احراز هویت تأیید شد',
  ntfsub_kyc_approved: 'سطح {tier}',
  ntf_kyc_rejected: 'مدارک تأیید نشد',
  ntfsub_kyc_rejected: 'جزئیات را در صفحهٔ احراز هویت ببینید',
  ntf_feedback_reply: 'تیم به پیام شما پاسخ داد',
  ntfsub_feedback_reply: 'بازخورد و گزارش مشکل',
  rateTitle: 'تجربهٔ معامله با {n} چطور بود؟',
  rateGood: 'خوب',
  rateBad: 'بد',
  rateComment: 'یک جمله برای دیگران (اختیاری)',
  rateSend: 'ثبت نظر',
  ratedThanks: 'ممنون! نظر شما ثبت شد.',
  traderProfile: 'پروفایل معامله‌گر',
  memberSince: 'عضو از {d}',
  positiveRatings: 'رضایت',
  medianRelease: 'معمولاً حدود {n} دقیقه پس از پرداخت آزاد می‌کند.',
  activeOffers: 'آگهی‌های فعال',
  reviews: 'نظرها',
  noReviews: 'هنوز نظری ثبت نشده است.',
  fromBuyer: 'از طرف خریدار',
  fromSeller: 'از طرف فروشنده',
  err_invalid_rating: 'خوب یا بد را انتخاب کنید.',
  err_already_rated: 'برای این معامله قبلاً نظر داده‌اید.',
  err_invalid_subscription: 'روشن کردن اعلان در این مرورگر ممکن نشد.',
})
Object.assign(strings.en, {
  notificationsTitle: 'Notifications',
  markAllRead: 'Mark all read',
  noNotifications: 'No notifications. New trades, arriving money and messages show up here.',
  unread: 'Unread',
  pushTitle: 'Phone notifications',
  pushSub: 'Know when the buyer has paid or USDT is released, even when the app is closed.',
  pushOn: 'On. The most important events appear on your phone.',
  pushDenied: 'Notifications are blocked in your browser settings.',
  pushEnable: 'Turn on',
  pushDisable: 'Turn off',
  ntf_trade_opened: 'New trade on your offer',
  ntfsub_trade_opened: '{amount} USDT · trade #{tradeId}',
  ntf_trade_paid: 'The buyer has paid',
  ntfsub_trade_paid: 'Check the money and release the USDT · #{tradeId}',
  ntf_trade_released: 'USDT released',
  ntfsub_trade_released: '{amount} USDT arrived in your wallet · #{tradeId}',
  ntf_trade_cancelled: 'Trade cancelled',
  ntfsub_trade_cancelled: 'Trade #{tradeId}',
  ntf_trade_disputed: 'Dispute opened',
  ntfsub_trade_disputed: 'Support is reviewing it · #{tradeId}',
  ntf_trade_resolved: 'Dispute decided',
  ntfsub_trade_resolved: 'See the result · #{tradeId}',
  ntf_trade_message: 'New message',
  ntfsub_trade_message: 'In trade #{tradeId}',
  ntf_deposit_credited: 'Deposit received',
  ntfsub_deposit_credited: '{amount} USDT',
  ntf_deposit_rejected: 'Deposit not approved',
  ntfsub_deposit_rejected: '{amount} USDT',
  ntf_withdrawal_sent: 'Withdrawal sent',
  ntfsub_withdrawal_sent: '{amount} USDT',
  ntf_withdrawal_rejected: 'Withdrawal not sent',
  ntfsub_withdrawal_rejected: 'The balance went back to your wallet',
  ntf_kyc_approved: 'Verification approved',
  ntfsub_kyc_approved: 'Level {tier}',
  ntf_kyc_rejected: 'Documents not approved',
  ntfsub_kyc_rejected: 'See the verification page for details',
  ntf_feedback_reply: 'The team replied to your message',
  ntfsub_feedback_reply: 'Feedback & problems',
  rateTitle: 'How was trading with {n}?',
  rateGood: 'Good',
  rateBad: 'Bad',
  rateComment: 'One sentence for others (optional)',
  rateSend: 'Submit',
  ratedThanks: 'Thank you! Your rating was saved.',
  traderProfile: 'Trader profile',
  memberSince: 'Member since {d}',
  positiveRatings: 'Positive',
  medianRelease: 'Usually releases about {n} min after payment.',
  activeOffers: 'Active offers',
  reviews: 'Reviews',
  noReviews: 'No reviews yet.',
  fromBuyer: 'From a buyer',
  fromSeller: 'From a seller',
  err_invalid_rating: 'Choose good or bad.',
  err_already_rated: 'You already rated this trade.',
  err_invalid_subscription: 'Notifications could not be turned on in this browser.',
})

// Safety: seller approval, counterparty requirements, blocking, trading pause.
Object.assign(strings.fa, {
  safetyTitle: 'امنیت و شرایط',
  requireAccept: 'اول من خریدار را تأیید کنم',
  requireAcceptSub: 'حساب دریافت شما فقط بعد از پذیرش شما به خریدار نشان داده می‌شود. هر درخواست {n} دقیقه منتظر پاسخ شما می‌ماند.',
  minTradesLabel: 'حداقل معاملهٔ تکمیل‌شدهٔ طرف مقابل',
  minAccountDaysLabel: 'حداقل عمر حساب طرف مقابل',
  requireIdLabel: 'فقط کاربران با هویت تأییدشده (سطح ۲)',
  anyValue: 'مهم نیست',
  daysN: '{n} روز',
  reqAccept: 'فروشنده خریدار را تأیید می‌کند',
  reqMinTrades: 'حداقل {n} معامله',
  reqMinDays: 'حساب بالای {n} روز',
  reqId: 'هویت تأییدشده',
  reqAcceptNote: 'بعد از درخواست شما، فروشنده حداکثر {n} دقیقه وقت دارد بپذیرد. حساب پرداخت پس از پذیرش نمایش داده می‌شود و زمان پرداخت از همان لحظه شروع می‌شود.',
  sendRequest: 'ارسال درخواست خرید',
  waitAccept: 'منتظر پذیرش فروشنده',
  waitAcceptSub: 'فروشنده درخواست شما را بررسی می‌کند. هنوز پولی نفرستید؛ حساب پرداخت بعد از پذیرش نمایش داده می‌شود.',
  reviewBuyer: 'درخواست خرید — بررسی کنید',
  reviewBuyerSub: 'اگر بپذیرید، حساب دریافت شما به این خریدار نشان داده می‌شود و زمان پرداخت شروع می‌شود.',
  accountAfterAccept: 'حساب فروشنده پس از پذیرش نمایش داده می‌شود.',
  aboutBuyer: 'دربارهٔ خریدار',
  newAccount: 'حساب تازه',
  idNotVerified: 'هویت تأییدنشده',
  acceptBuyer: 'پذیرفتن و نمایش حساب',
  declineBuyer: 'رد کردن',
  declineBlock: 'رد و مسدود کردن این کاربر',
  confirmDeclineBlock: 'درخواست رد می‌شود. این کاربر دیگر آگهی‌های شما را نمی‌بیند و نمی‌تواند با شما معامله کند.',
  acceptTip: 'با حساب‌های تازه، بدون معامله و بدون نظر با احتیاط رفتار کنید. شمارهٔ شخصی خود را در گفتگو ننویسید.',
  blockUser: 'مسدود کردن',
  unblockUser: 'رفع مسدودی',
  blockConfirm: 'این کاربر آگهی‌های شما را نمی‌بیند و نمی‌تواند با شما معامله کند. شما هم آگهی‌های او را نمی‌بینید.',
  blockedNote: 'این کاربر را مسدود کرده‌اید.',
  blockedUsers: 'کاربران مسدودشده',
  blockedUsersSub: 'کسانی که مسدود کرده‌اید آگهی‌های شما را نمی‌بینند و نمی‌توانند با شما معامله کنند.',
  noBlocked: 'کسی را مسدود نکرده‌اید.',
  blockedToast: 'کاربر مسدود شد',
  unblockedToast: 'مسدودی برداشته شد',
  frozenUntil: 'معامله متوقف تا {d}',
  unfreeze: 'رفع توقف معامله',
  rule_reveal_abuse: 'لغو پس از دیدن حساب فروشنده',
  sys_trade_awaiting_accept: 'درخواست خرید ثبت شد · تتر فروشنده در امانت قفل شد · منتظر پذیرش فروشنده',
  sys_trade_accepted: 'فروشنده پذیرفت · زمان پرداخت شروع شد',
  sys_trade_declined_by_seller: 'فروشنده درخواست را رد کرد · سفارش لغو شد',
  sys_trade_not_accepted: 'فروشنده به‌موقع پاسخ نداد · سفارش لغو شد',
  ntf_trade_request: 'درخواست خرید تازه',
  ntfsub_trade_request: '{amount} تتر · بپذیرید یا رد کنید · #{tradeId}',
  ntf_trade_accepted: 'فروشنده درخواست شما را پذیرفت',
  ntfsub_trade_accepted: 'حالا پول را بپردازید · #{tradeId}',
  ntf_trade_declined: 'درخواست شما پذیرفته نشد',
  ntfsub_trade_declined: 'آگهی دیگری را امتحان کنید · #{tradeId}',
  err_requirements_not_met: 'حساب شما هنوز شرایط این آگهی را ندارد (تعداد معامله، عمر حساب یا تأیید هویت). شرایط را در صفحهٔ آگهی ببینید.',
  err_trading_paused: 'معامله برای حساب شما موقتاً متوقف شده است، چون چند معامله را پس از دیدن حساب فروشنده لغو کردید. برای بررسی با پشتیبانی تماس بگیرید.',
  err_awaiting_acceptance: 'فروشنده هنوز این معامله را نپذیرفته است.',
  err_new_account_limit: 'حساب‌های تازه در هفتهٔ اول حداکثر {max} تتر در هر معامله می‌توانند معامله کنند.',
  err_invalid_requirements: 'شرایط آگهی درست نیست.',
  st_awaiting_buyer: 'منتظر پذیرش فروشنده',
  st_awaiting_seller: 'درخواست خرید · منتظر پاسخ شما',
})
Object.assign(strings.en, {
  safetyTitle: 'Safety & requirements',
  requireAccept: 'I approve each buyer first',
  requireAcceptSub: 'Your receiving account is shown to a buyer only after you accept. Each request waits {n} minutes for your answer.',
  minTradesLabel: 'Counterparty’s min. completed trades',
  minAccountDaysLabel: 'Counterparty’s min. account age',
  requireIdLabel: 'Only ID-verified users (level 2)',
  anyValue: 'Any',
  daysN: '{n} days',
  reqAccept: 'Seller approves buyers',
  reqMinTrades: 'At least {n} trades',
  reqMinDays: 'Account over {n} days',
  reqId: 'Verified ID',
  reqAcceptNote: 'After you send a request the seller has up to {n} minutes to accept. The payment account appears once they accept, and the payment timer starts then.',
  sendRequest: 'Send buy request',
  waitAccept: 'Waiting for the seller',
  waitAcceptSub: 'The seller is reviewing your request. Don’t send money yet — the payment account appears once they accept.',
  reviewBuyer: 'Buy request — review it',
  reviewBuyerSub: 'If you accept, your receiving account is shown to this buyer and the payment timer starts.',
  accountAfterAccept: 'The seller’s account appears once they accept.',
  aboutBuyer: 'About the buyer',
  newAccount: 'New account',
  idNotVerified: 'ID not verified',
  acceptBuyer: 'Accept & show account',
  declineBuyer: 'Decline',
  declineBlock: 'Decline and block this user',
  confirmDeclineBlock: 'The request is declined. This user will no longer see your offers or be able to trade with you.',
  acceptTip: 'Be careful with brand-new accounts that have no trades or reviews. Don’t share your personal number in chat.',
  blockUser: 'Block',
  unblockUser: 'Unblock',
  blockConfirm: 'This user will not see your offers or be able to trade with you, and you won’t see theirs.',
  blockedNote: 'You blocked this user.',
  blockedUsers: 'Blocked users',
  blockedUsersSub: 'People you block can’t see your offers or trade with you.',
  noBlocked: 'You haven’t blocked anyone.',
  blockedToast: 'User blocked',
  unblockedToast: 'User unblocked',
  frozenUntil: 'Trading paused until {d}',
  unfreeze: 'Lift trading pause',
  rule_reveal_abuse: 'Cancels after seeing seller accounts',
  sys_trade_awaiting_accept: 'Buy request sent · seller’s USDT locked in escrow · waiting for the seller',
  sys_trade_accepted: 'Seller accepted · payment timer started',
  sys_trade_declined_by_seller: 'The seller declined the request · order cancelled',
  sys_trade_not_accepted: 'The seller didn’t answer in time · order cancelled',
  ntf_trade_request: 'New buy request',
  ntfsub_trade_request: '{amount} USDT · accept or decline · #{tradeId}',
  ntf_trade_accepted: 'The seller accepted your request',
  ntfsub_trade_accepted: 'Send the payment now · #{tradeId}',
  ntf_trade_declined: 'Your request was declined',
  ntfsub_trade_declined: 'Try another offer · #{tradeId}',
  err_requirements_not_met: 'Your account doesn’t meet this offer’s requirements yet (trades, account age or verified ID). See them on the offer page.',
  err_trading_paused: 'Trading is paused for your account because several trades were cancelled after the seller’s account was shown. Contact support to review it.',
  err_awaiting_acceptance: 'The seller hasn’t accepted this trade yet.',
  err_new_account_limit: 'In their first week, new accounts can trade at most {max} USDT per trade.',
  err_invalid_requirements: 'The offer requirements are not valid.',
  st_awaiting_buyer: 'Waiting for the seller',
  st_awaiting_seller: 'Buy request · your answer needed',
})
