// UI strings. Dari (fa) is the primary language; English (en) is the fallback.
export const strings = {
  fa: {
    brandTagline: 'مستقیم با افغانی',
    welcomeTitle: 'تتر بخرید و بفروشید،',
    welcomeSub: 'بازار همتا‌به‌همتا با تضمین امانی — تتر فروشنده تا تأیید پرداخت شما نزد پلتفرم قفل می‌ماند.',
    createAccount: 'ایجاد حساب رایگان',
    haveAccount: 'حساب دارم — ورود',
    browseMarket: 'دیدن بازار بدون ورود',
    language: 'زبان',

    welcomeBack: 'خوش آمدید',
    loginSub: 'برای خرید و فروش تتر وارد حساب خود شوید.',
    registerTitle: 'ایجاد حساب',
    registerSub: 'نام کاربری و رمز عبور انتخاب کنید.',
    login: 'ورود',
    register: 'ثبت نام',
    username: 'نام کاربری',
    usernameHint: '۳ تا ۲۴ حرف انگلیسی، عدد یا _',
    displayName: 'نام نمایشی',
    phone: 'شماره موبایل',
    password: 'رمز عبور',
    passwordHint: 'حداقل ۸ حرف',
    showPassword: 'نمایش رمز',
    secureNote: 'اتصال رمزگذاری‌شده و تأیید دومرحله‌ای برای برداشت‌ها',
    back: 'بازگشت',
    close: 'بستن',

    greeting: 'سلام',
    totalBalance: 'موجودی کل',
    hideBalance: 'پنهان کردن موجودی',
    available: 'قابل استفاده',
    inEscrow: 'در امانت',
    approxAfn: '≈ {v} افغانی',
    deposit: 'واریز',
    withdraw: 'برداشت',
    buy: 'خرید',
    sell: 'فروش',
    bestBuy: 'بهترین قیمت خرید',
    bestSell: 'بهترین قیمت فروش',
    goMarket: 'رفتن به بازار',
    activeTrades: 'معامله‌های فعال',
    all: 'همه',
    recentActivity: 'فعالیت اخیر',
    noActivity: 'هنوز فعالیتی ندارید. با واریز تتر یا خرید از بازار شروع کنید.',

    market: 'بازار P2P',
    marketSub: 'معامله مستقیم با کاربران',
    buyUsdt: 'خرید USDT',
    sellUsdt: 'فروش USDT',
    amountAfnFilter: 'مبلغ مورد نظر به افغانی',
    filters: 'فیلترها',
    newOffer: 'آگهی جدید',
    trades: 'معامله',
    completion: 'تکمیل',
    perUsdt: 'برای هر USDT',
    availableAmt: 'موجود',
    limits: 'محدوده',
    noOffers: 'فعلاً آگهی‌ای با این شرایط نیست.',
    postFirstOffer: 'اولین آگهی را بگذارید',

    escrow: 'امانی',
    memberTrades: 'معاملات',
    payWindow: 'مهلت پرداخت',
    minutes: '{n} دقیقه',
    youPay: 'مبلغ پرداخت',
    youSell: 'مقدار فروش',
    youReceive: 'دریافت می‌کنید',
    inAfn: 'افغانی',
    max: 'حداکثر',
    fee: 'کمیشن',
    paymentMethod: 'روش پرداخت',
    sellerTerms: 'شرایط آگهی‌دهنده',
    escrowNote: 'تتر فروشنده تا پایان معامله در امانت پلتفرم قفل است.',
    buyAmount: 'خرید {v} USDT',
    sellAmount: 'فروش {v} USDT',
    loginToTrade: 'برای معامله وارد شوید',
    needAccountFor: 'برای فروش، ابتدا حساب دریافت {m} خود را در «حساب من» ثبت کنید.',

    order: 'سفارش',
    buyFrom: 'خرید از {n}',
    sellTo: 'فروش به {n}',
    payNow: 'مبلغ را پرداخت کنید',
    payNowSub: 'اگر تا پایان زمان پرداخت نکنید، سفارش خودکار لغو می‌شود.',
    waitBuyer: 'منتظر پرداخت خریدار',
    waitBuyerSub: 'پس از پرداخت خریدار، حساب خود را بررسی و تتر را آزاد کنید.',
    waitSeller: 'منتظر تأیید فروشنده',
    waitSellerSub: 'فروشنده پرداخت شما را بررسی می‌کند و تتر را آزاد می‌کند.',
    checkPayment: 'خریدار پرداخت کرد',
    checkPaymentSub: 'فقط پس از دیدن پول در حساب خود، تتر را آزاد کنید.',
    disputed: 'در حال داوری',
    disputedSub: 'پشتیبانی شواهد هر دو طرف را بررسی می‌کند. تتر تا تصمیم داور قفل می‌ماند.',
    stepPay: 'پرداخت',
    stepConfirm: 'تأیید فروشنده',
    stepReceive: 'دریافت',
    amountToPay: 'مبلغ قابل پرداخت',
    amountToReceive: 'مبلغ دریافتی شما',
    copy: 'کپی',
    copied: 'کپی شد',
    price: 'قیمت',
    receiveNet: 'دریافتی خریدار',
    recipientName: 'نام گیرنده',
    accountNumber: 'شماره حساب',
    noAccountInfo: 'فروشنده هنوز جزئیات حساب را ثبت نکرده — در گفتگو بپرسید.',
    payWarning: 'فقط از حساب به نام خودتان پرداخت کنید و در توضیحات پرداخت کلمهٔ «USDT» ننویسید.',
    releaseWarning: 'هرگز پیش از رسیدن پول به حساب خود تتر را آزاد نکنید. رسید عکس کافی نیست.',
    iPaid: 'پرداخت کردم',
    cancelOrder: 'لغو سفارش',
    confirmCancel: 'سفارش لغو شود؟ اگر پول فرستاده‌اید لغو نکنید.',
    release: 'پول را گرفتم — آزادسازی تتر',
    confirmRelease: 'آیا مطمئن هستید مبلغ {v} افغانی به حساب شما رسیده است؟ این کار قابل برگشت نیست.',
    openDispute: 'شکایت / داوری',
    disputeReason: 'دلیل شکایت',
    disputePlaceholder: 'چه اتفاقی افتاده؟ مثلاً: پول را فرستادم ولی فروشنده پاسخ نمی‌دهد.',
    submit: 'ثبت',
    cancel: 'انصراف',
    confirm: 'تأیید',
    chat: 'گفتگو',
    tradeDone: 'معامله با موفقیت انجام شد',
    addedToWallet: 'به کیف پول شما اضافه شد و قابل استفاده است.',
    soldDone: 'تتر فروخته شد و به خریدار رسید.',
    tradeCancelled: 'سفارش لغو شد',
    tradeCancelledSub: 'تتر امانی به فروشنده برگشت.',
    orderNo: 'شماره سفارش',
    counterparty: 'طرف معامله',
    paid: 'پرداخت شده',
    viewWallet: 'مشاهده کیف پول',
    newTrade: 'معامله جدید',

    online: 'آنلاین',
    writeMessage: 'پیام بنویسید…',
    send: 'ارسال',
    chatSafety: 'هرگز خارج از پلتفرم تتر نفرستید — پشتیبانی گفتگو را می‌بیند.',
    noMessages: 'هنوز پیامی نیست. سلام کنید!',
    sys_trade_opened: 'سفارش ایجاد شد · تتر فروشنده در امانت قفل شد',
    sys_trade_marked_paid: 'خریدار پرداخت را علامت زد · منتظر تأیید فروشنده',
    sys_trade_released: 'فروشنده تتر را آزاد کرد · معامله تکمیل شد',
    sys_trade_cancelled_by_buyer: 'خریدار سفارش را لغو کرد',
    sys_trade_expired: 'مهلت پرداخت تمام شد · سفارش لغو شد',
    sys_trade_disputed: 'شکایت ثبت شد · پشتیبانی بررسی می‌کند',
    sys_trade_resolved_buyer: 'داور به نفع خریدار تصمیم گرفت',
    sys_trade_resolved_seller: 'داور به نفع فروشنده تصمیم گرفت',

    wallet: 'کیف پول',
    network: 'شبکه',
    tether: 'تتر',
    history: 'تاریخچه',
    today: 'امروز',
    yesterday: 'دیروز',
    kind_deposit: 'واریز تتر',
    kind_withdraw_lock: 'درخواست برداشت',
    kind_withdraw_refund: 'برداشت رد شد · بازگشت',
    kind_withdrawal: 'برداشت ارسال شد',
    kind_offer_lock: 'قفل برای آگهی فروش',
    kind_offer_unlock: 'آزاد شدن آگهی',
    kind_trade_lock: 'قفل برای معامله',
    kind_trade_refund: 'بازگشت از معامله',
    kind_escrow_release: 'فروش تتر',
    kind_trade_receive: 'خرید تتر',
    status_pending: 'در حال بررسی',
    status_approved: 'تأیید شد',
    status_rejected: 'رد شد',
    status_sent: 'ارسال شد',

    depositUsdt: 'واریز USDT',
    tronNetwork: 'شبکهٔ ترون (TRC20)',
    onlyNetwork: 'تنها شبکهٔ پشتیبانی‌شده',
    depositAddress: 'آدرس واریز',
    depositWarning: 'فقط USDT روی شبکهٔ TRC20 بفرستید. ارسال از شبکه‌های دیگر مثل ERC20 یا BEP20 باعث از دست رفتن دارایی می‌شود.',
    afterSending: 'پس از ارسال، مقدار و شناسهٔ تراکنش (TxID) را وارد کنید',
    amount: 'مقدار',
    txid: 'شناسهٔ تراکنش (TxID)',
    paste: 'چسباندن',
    submitDeposit: 'ثبت واریز',
    depositSubmitted: 'واریز ثبت شد و پس از بررسی روی شبکه به موجودی شما اضافه می‌شود.',
    recentDeposits: 'واریزهای اخیر',

    withdrawUsdt: 'برداشت USDT',
    destAddress: 'آدرس مقصد',
    destHint: 'آدرس باید با حرف T شروع شود و روی شبکهٔ ترون باشد.',
    networkFee: 'کارمزد شبکه',
    totalDeducted: 'کسر از موجودی',
    destReceives: 'دریافتی مقصد',
    minWithdraw: 'حداقل برداشت: {v} USDT',
    confirmWithdraw: 'تأیید برداشت',
    withdrawNote: 'برداشت‌ها پس از بررسی امنیتی روی شبکه ارسال می‌شوند.',
    withdrawSubmitted: 'درخواست برداشت ثبت شد.',
    recentWithdrawals: 'برداشت‌های اخیر',

    createOffer: 'ایجاد آگهی',
    iWantBuy: 'می‌خواهم بخرم',
    iWantSell: 'می‌خواهم بفروشم',
    pricePerUsdt: 'قیمت هر USDT',
    marketBest: 'بهترین قیمت فعلی بازار: {v} ؋',
    totalToSell: 'مقدار کل برای فروش',
    totalToBuy: 'مقدار کل برای خرید',
    perTradeLimits: 'محدودهٔ هر معامله (افغانی)',
    min: 'حداقل',
    receiveMethods: 'روش‌های دریافت پول',
    payMethods: 'روش‌های پرداخت شما',
    buyerWindow: 'مهلت پرداخت خریدار',
    terms: 'شرایط معامله (اختیاری)',
    termsPlaceholder: 'مثلاً: فقط از حساب به نام خودتان پرداخت کنید.',
    lockNote: '{v} USDT تا بسته شدن آگهی در امانت قفل می‌شود.',
    publishOffer: 'انتشار آگهی',
    offerPublished: 'آگهی منتشر شد.',
    missingAccounts: 'برای این روش‌ها حساب دریافت ثبت نکرده‌اید: {m}',
    addAccount: 'افزودن حساب',

    orders: 'سفارش‌ها',
    active: 'فعال',
    completed: 'تکمیل‌شده',
    myOffers: 'آگهی‌های من',
    noActive: 'معاملهٔ فعالی ندارید.',
    noCompleted: 'هنوز معامله‌ای تکمیل نشده.',
    noMyOffers: 'آگهی‌ای ندارید.',
    st_pending_payment: 'در انتظار پرداخت',
    st_pending_payment_buyer: 'در انتظار پرداخت شما',
    st_paid: 'پرداخت شد — منتظر فروشنده',
    st_paid_seller: 'خریدار پرداخت کرد — حساب خود را بررسی کنید',
    st_disputed: 'در حال داوری',
    st_completed: 'تکمیل شد',
    st_cancelled: 'لغو شد',
    offer_active: 'فعال',
    offer_paused: 'متوقف',
    offer_closed: 'بسته',
    pause: 'توقف',
    resume: 'فعال‌سازی',
    closeOffer: 'بستن آگهی',
    remaining: 'باقی‌مانده',

    profile: 'حساب من',
    verified: 'تأییدشده',
    completionRate: 'نرخ تکمیل',
    myPaymentAccounts: 'حساب‌های دریافت پول',
    noPaymentAccounts: 'هنوز حسابی ثبت نکرده‌اید.',
    holderName: 'نام صاحب حساب',
    accountOrPhone: 'شماره حساب یا موبایل',
    save: 'ذخیره',
    remove: 'حذف',
    appearance: 'حالت نمایش',
    dark: 'تیره',
    light: 'روشن',
    security: 'امنیت و تأیید دومرحله‌ای',
    soon: 'به‌زودی',
    support: 'پشتیبانی',
    logout: 'خروج از حساب',
    adminPanel: 'پنل مدیریت',

    home: 'خانه',

    err_network_error: 'اتصال برقرار نشد. اینترنت خود را بررسی کنید.',
    err_server_error: 'خطای سرور. کمی بعد دوباره تلاش کنید.',
    err_unauthorized: 'لطفاً وارد حساب شوید.',
    err_forbidden: 'اجازهٔ این کار را ندارید.',
    err_not_found: 'پیدا نشد.',
    err_too_many_requests: 'تلاش زیاد. چند دقیقه صبر کنید.',
    err_invalid_credentials: 'نام کاربری یا رمز عبور اشتباه است.',
    err_account_blocked: 'حساب شما مسدود شده است. با پشتیبانی تماس بگیرید.',
    err_invalid_username: 'نام کاربری باید ۳ تا ۲۴ حرف انگلیسی، عدد یا _ باشد.',
    err_weak_password: 'رمز عبور باید حداقل ۸ حرف باشد.',
    err_invalid_phone: 'شماره موبایل درست نیست.',
    err_username_taken: 'این نام کاربری گرفته شده است.',
    err_insufficient_balance: 'موجودی کافی نیست.',
    err_invalid_amount: 'مقدار درست نیست.',
    err_invalid_price: 'قیمت درست نیست.',
    err_invalid_limits: 'محدودهٔ معامله درست نیست.',
    err_invalid_payment_methods: 'حداقل یک روش پرداخت انتخاب کنید.',
    err_invalid_payment_method: 'روش پرداخت درست نیست.',
    err_invalid_payment_account: 'نام صاحب حساب و شماره را وارد کنید.',
    err_missing_payment_account: 'ابتدا حساب دریافت پول را برای این روش در «حساب من» ثبت کنید.',
    err_invalid_payment_window: 'مهلت پرداخت درست نیست.',
    err_offer_unavailable: 'این آگهی دیگر در دسترس نیست.',
    err_own_offer: 'نمی‌توانید با آگهی خودتان معامله کنید.',
    err_exceeds_available: 'مقدار بیشتر از موجودی آگهی است.',
    err_outside_limits: 'مبلغ خارج از محدودهٔ آگهی است.',
    err_too_many_open_trades: 'حداکثر ۵ معاملهٔ باز همزمان مجاز است.',
    err_invalid_state: 'وضعیت معامله تغییر کرده است. صفحه را تازه کنید.',
    err_reason_required: 'دلیل شکایت را بنویسید.',
    err_empty_message: 'پیام خالی است.',
    err_invalid_txid: 'شناسهٔ تراکنش درست نیست (۶۴ کاراکتر).',
    err_duplicate_txid: 'این تراکنش قبلاً ثبت شده است.',
    err_invalid_address: 'آدرس TRC20 درست نیست.',
    err_below_minimum: 'مقدار کمتر از حداقل برداشت است.',
    err_offer_closed: 'آگهی بسته شده است.',
  },

  en: {
    brandTagline: 'directly with Afghani',
    welcomeTitle: 'Buy and sell Tether,',
    welcomeSub: 'Peer-to-peer market with escrow — the seller’s USDT stays locked by the platform until your payment is confirmed.',
    createAccount: 'Create a free account',
    haveAccount: 'I have an account — log in',
    browseMarket: 'Browse the market without logging in',
    language: 'Language',

    welcomeBack: 'Welcome back',
    loginSub: 'Log in to buy and sell Tether.',
    registerTitle: 'Create account',
    registerSub: 'Choose a username and password.',
    login: 'Log in',
    register: 'Sign up',
    username: 'Username',
    usernameHint: '3–24 letters, digits or _',
    displayName: 'Display name',
    phone: 'Mobile number',
    password: 'Password',
    passwordHint: 'At least 8 characters',
    showPassword: 'Show password',
    secureNote: 'Encrypted connection and two-step confirmation for withdrawals',
    back: 'Back',
    close: 'Close',

    greeting: 'Hello',
    totalBalance: 'Total balance',
    hideBalance: 'Hide balance',
    available: 'Available',
    inEscrow: 'In escrow',
    approxAfn: '≈ {v} AFN',
    deposit: 'Deposit',
    withdraw: 'Withdraw',
    buy: 'Buy',
    sell: 'Sell',
    bestBuy: 'Best buy price',
    bestSell: 'Best sell price',
    goMarket: 'Go to market',
    activeTrades: 'Active trades',
    all: 'All',
    recentActivity: 'Recent activity',
    noActivity: 'No activity yet. Start by depositing USDT or buying from the market.',

    market: 'P2P market',
    marketSub: 'Trade directly with people',
    buyUsdt: 'Buy USDT',
    sellUsdt: 'Sell USDT',
    amountAfnFilter: 'Amount in AFN',
    filters: 'Filters',
    newOffer: 'New offer',
    trades: 'trades',
    completion: 'completion',
    perUsdt: 'per USDT',
    availableAmt: 'Available',
    limits: 'Limits',
    noOffers: 'No offers match right now.',
    postFirstOffer: 'Post the first offer',

    escrow: 'Escrow',
    memberTrades: 'Trades',
    payWindow: 'Payment window',
    minutes: '{n} min',
    youPay: 'You pay',
    youSell: 'You sell',
    youReceive: 'You receive',
    inAfn: 'AFN',
    max: 'Max',
    fee: 'Fee',
    paymentMethod: 'Payment method',
    sellerTerms: 'Advertiser terms',
    escrowNote: 'The seller’s USDT is locked in platform escrow until the trade ends.',
    buyAmount: 'Buy {v} USDT',
    sellAmount: 'Sell {v} USDT',
    loginToTrade: 'Log in to trade',
    needAccountFor: 'To sell, first add your {m} receiving account in Profile.',

    order: 'Order',
    buyFrom: 'Buy from {n}',
    sellTo: 'Sell to {n}',
    payNow: 'Please make the payment',
    payNowSub: 'If you don’t pay before the timer ends, the order is cancelled automatically.',
    waitBuyer: 'Waiting for the buyer to pay',
    waitBuyerSub: 'After the buyer pays, check your account and release the USDT.',
    waitSeller: 'Waiting for the seller',
    waitSellerSub: 'The seller is checking your payment and will release the USDT.',
    checkPayment: 'The buyer has paid',
    checkPaymentSub: 'Release the USDT only after you see the money in your account.',
    disputed: 'Under review',
    disputedSub: 'Support is reviewing both sides. The USDT stays locked until a decision.',
    stepPay: 'Pay',
    stepConfirm: 'Seller confirms',
    stepReceive: 'Receive',
    amountToPay: 'Amount to pay',
    amountToReceive: 'Amount you receive',
    copy: 'Copy',
    copied: 'Copied',
    price: 'Price',
    receiveNet: 'Buyer receives',
    recipientName: 'Recipient name',
    accountNumber: 'Account number',
    noAccountInfo: 'The seller hasn’t added account details yet — ask in chat.',
    payWarning: 'Only pay from an account in your own name and don’t write “USDT” in the payment note.',
    releaseWarning: 'Never release USDT before the money reaches your account. A receipt photo is not enough.',
    iPaid: 'I have paid',
    cancelOrder: 'Cancel order',
    confirmCancel: 'Cancel this order? Don’t cancel if you already sent money.',
    release: 'I got the money — release USDT',
    confirmRelease: 'Are you sure {v} AFN has arrived in your account? This cannot be undone.',
    openDispute: 'Open dispute',
    disputeReason: 'Reason',
    disputePlaceholder: 'What happened? e.g. I paid but the seller does not respond.',
    submit: 'Submit',
    cancel: 'Cancel',
    confirm: 'Confirm',
    chat: 'Chat',
    tradeDone: 'Trade completed',
    addedToWallet: 'Added to your wallet and ready to use.',
    soldDone: 'USDT sold and delivered to the buyer.',
    tradeCancelled: 'Order cancelled',
    tradeCancelledSub: 'The escrowed USDT went back to the seller.',
    orderNo: 'Order no.',
    counterparty: 'Counterparty',
    paid: 'Paid',
    viewWallet: 'View wallet',
    newTrade: 'New trade',

    online: 'Online',
    writeMessage: 'Write a message…',
    send: 'Send',
    chatSafety: 'Never send USDT outside the platform — support can see this chat.',
    noMessages: 'No messages yet. Say hello!',
    sys_trade_opened: 'Order created · seller’s USDT locked in escrow',
    sys_trade_marked_paid: 'Buyer marked as paid · waiting for seller',
    sys_trade_released: 'Seller released the USDT · trade completed',
    sys_trade_cancelled_by_buyer: 'Buyer cancelled the order',
    sys_trade_expired: 'Payment window ended · order cancelled',
    sys_trade_disputed: 'Dispute opened · support is reviewing',
    sys_trade_resolved_buyer: 'Resolved in favour of the buyer',
    sys_trade_resolved_seller: 'Resolved in favour of the seller',

    wallet: 'Wallet',
    network: 'Network',
    tether: 'Tether',
    history: 'History',
    today: 'Today',
    yesterday: 'Yesterday',
    kind_deposit: 'USDT deposit',
    kind_withdraw_lock: 'Withdrawal requested',
    kind_withdraw_refund: 'Withdrawal rejected · refunded',
    kind_withdrawal: 'Withdrawal sent',
    kind_offer_lock: 'Locked for sell offer',
    kind_offer_unlock: 'Offer unlocked',
    kind_trade_lock: 'Locked for trade',
    kind_trade_refund: 'Returned from trade',
    kind_escrow_release: 'Sold USDT',
    kind_trade_receive: 'Bought USDT',
    status_pending: 'Under review',
    status_approved: 'Approved',
    status_rejected: 'Rejected',
    status_sent: 'Sent',

    depositUsdt: 'Deposit USDT',
    tronNetwork: 'Tron network (TRC20)',
    onlyNetwork: 'The only supported network',
    depositAddress: 'Deposit address',
    depositWarning: 'Send only USDT on the TRC20 network. Sending from other networks such as ERC20 or BEP20 will lose the funds.',
    afterSending: 'After sending, enter the amount and transaction ID (TxID)',
    amount: 'Amount',
    txid: 'Transaction ID (TxID)',
    paste: 'Paste',
    submitDeposit: 'Submit deposit',
    depositSubmitted: 'Deposit submitted. It will be credited after on-chain review.',
    recentDeposits: 'Recent deposits',

    withdrawUsdt: 'Withdraw USDT',
    destAddress: 'Destination address',
    destHint: 'The address must start with T and be on the Tron network.',
    networkFee: 'Network fee',
    totalDeducted: 'Deducted from balance',
    destReceives: 'Destination receives',
    minWithdraw: 'Minimum withdrawal: {v} USDT',
    confirmWithdraw: 'Confirm withdrawal',
    withdrawNote: 'Withdrawals are sent on-chain after a security review.',
    withdrawSubmitted: 'Withdrawal requested.',
    recentWithdrawals: 'Recent withdrawals',

    createOffer: 'Create offer',
    iWantBuy: 'I want to buy',
    iWantSell: 'I want to sell',
    pricePerUsdt: 'Price per USDT',
    marketBest: 'Current best market price: {v} AFN',
    totalToSell: 'Total to sell',
    totalToBuy: 'Total to buy',
    perTradeLimits: 'Per-trade limits (AFN)',
    min: 'Min',
    receiveMethods: 'How you get paid',
    payMethods: 'How you pay',
    buyerWindow: 'Buyer payment window',
    terms: 'Terms (optional)',
    termsPlaceholder: 'e.g. Only pay from an account in your own name.',
    lockNote: '{v} USDT is locked in escrow until the offer is closed.',
    publishOffer: 'Publish offer',
    offerPublished: 'Offer published.',
    missingAccounts: 'You have no receiving account for: {m}',
    addAccount: 'Add account',

    orders: 'Orders',
    active: 'Active',
    completed: 'Completed',
    myOffers: 'My offers',
    noActive: 'No active trades.',
    noCompleted: 'No completed trades yet.',
    noMyOffers: 'You have no offers.',
    st_pending_payment: 'Waiting for payment',
    st_pending_payment_buyer: 'Waiting for your payment',
    st_paid: 'Paid — waiting for seller',
    st_paid_seller: 'Buyer paid — check your account',
    st_disputed: 'Under review',
    st_completed: 'Completed',
    st_cancelled: 'Cancelled',
    offer_active: 'Active',
    offer_paused: 'Paused',
    offer_closed: 'Closed',
    pause: 'Pause',
    resume: 'Resume',
    closeOffer: 'Close offer',
    remaining: 'Remaining',

    profile: 'Profile',
    verified: 'Verified',
    completionRate: 'Completion',
    myPaymentAccounts: 'Receiving accounts',
    noPaymentAccounts: 'No accounts added yet.',
    holderName: 'Account holder name',
    accountOrPhone: 'Account or mobile number',
    save: 'Save',
    remove: 'Remove',
    appearance: 'Appearance',
    dark: 'Dark',
    light: 'Light',
    security: 'Security & two-step verification',
    soon: 'Soon',
    support: 'Support',
    logout: 'Log out',
    adminPanel: 'Admin panel',

    home: 'Home',

    err_network_error: 'Could not connect. Check your internet.',
    err_server_error: 'Server error. Please try again shortly.',
    err_unauthorized: 'Please log in.',
    err_forbidden: 'You are not allowed to do this.',
    err_not_found: 'Not found.',
    err_too_many_requests: 'Too many attempts. Wait a few minutes.',
    err_invalid_credentials: 'Wrong username or password.',
    err_account_blocked: 'Your account is blocked. Contact support.',
    err_invalid_username: 'Username must be 3–24 letters, digits or _.',
    err_weak_password: 'Password must be at least 8 characters.',
    err_invalid_phone: 'Invalid mobile number.',
    err_username_taken: 'This username is taken.',
    err_insufficient_balance: 'Insufficient balance.',
    err_invalid_amount: 'Invalid amount.',
    err_invalid_price: 'Invalid price.',
    err_invalid_limits: 'Invalid trade limits.',
    err_invalid_payment_methods: 'Choose at least one payment method.',
    err_invalid_payment_method: 'Invalid payment method.',
    err_invalid_payment_account: 'Enter the holder name and number.',
    err_missing_payment_account: 'First add a receiving account for this method in Profile.',
    err_invalid_payment_window: 'Invalid payment window.',
    err_offer_unavailable: 'This offer is no longer available.',
    err_own_offer: 'You can’t trade with your own offer.',
    err_exceeds_available: 'Amount exceeds what the offer has left.',
    err_outside_limits: 'Amount is outside the offer limits.',
    err_too_many_open_trades: 'At most 5 open trades at a time.',
    err_invalid_state: 'The trade changed. Refresh the page.',
    err_reason_required: 'Describe the problem.',
    err_empty_message: 'Message is empty.',
    err_invalid_txid: 'Invalid transaction ID (64 characters).',
    err_duplicate_txid: 'This transaction was already submitted.',
    err_invalid_address: 'Invalid TRC20 address.',
    err_below_minimum: 'Below the minimum withdrawal.',
    err_offer_closed: 'The offer is closed.',
  },
}

export const paymentMethodLabels = {
  fa: { hesabpay: 'HesabPay', mpaisa: 'M-Paisa', mhawala: 'M-Hawala', bank: 'حساب بانکی', hawala: 'حواله', cash: 'نقدی حضوری' },
  en: { hesabpay: 'HesabPay', mpaisa: 'M-Paisa', mhawala: 'M-Hawala', bank: 'Bank account', hawala: 'Hawala', cash: 'Cash in person' },
}
