-- Phase 10: notifications (in-app + web push outbox), push subscriptions, trade ratings.
SET search_path TO app, public;

-- Written in the same transaction as the event; pushed_at IS NULL = still in the push outbox.
CREATE TABLE notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users(id),
  kind text NOT NULL,
  data text NOT NULL DEFAULT '{}',
  trade_id bigint REFERENCES trades(id),
  read_at bigint,
  pushed_at bigint,
  created_at bigint NOT NULL
);
CREATE INDEX notifications_user ON notifications (user_id, id DESC);
CREATE INDEX notifications_unread ON notifications (user_id) WHERE read_at IS NULL;
CREATE INDEX notifications_outbox ON notifications (id) WHERE pushed_at IS NULL;

CREATE TABLE push_subscriptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users(id),
  endpoint text NOT NULL UNIQUE,
  p256dh text NOT NULL,
  auth text NOT NULL,
  lang text NOT NULL DEFAULT 'fa' CHECK (lang IN ('fa','en')),
  failures integer NOT NULL DEFAULT 0,
  created_at bigint NOT NULL,
  last_ok_at bigint
);
CREATE INDEX push_subscriptions_user ON push_subscriptions (user_id);

-- One rating per side per completed trade.
CREATE TABLE trade_ratings (
  trade_id bigint NOT NULL REFERENCES trades(id),
  rater_id bigint NOT NULL REFERENCES users(id),
  ratee_id bigint NOT NULL REFERENCES users(id),
  positive boolean NOT NULL,
  comment text,
  created_at bigint NOT NULL,
  PRIMARY KEY (trade_id, rater_id)
);
CREATE INDEX trade_ratings_ratee ON trade_ratings (ratee_id, created_at DESC);

DO $$
DECLARE t record;
BEGIN
  FOR t IN SELECT tablename FROM pg_tables WHERE schemaname = 'app' LOOP
    EXECUTE format('ALTER TABLE app.%I ENABLE ROW LEVEL SECURITY', t.tablename);
  END LOOP;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    EXECUTE 'REVOKE ALL ON ALL TABLES IN SCHEMA app FROM anon, authenticated';
    EXECUTE 'REVOKE ALL ON ALL SEQUENCES IN SCHEMA app FROM anon, authenticated';
  END IF;
END $$;
