-- P2PPay schema for PostgreSQL / Supabase.
--
-- Everything lives in the private schema "app". It is NOT exposed through Supabase's Data API:
-- the anon/authenticated roles get no privileges and every table has RLS enabled with no policies,
-- so only the API server (connecting as the database owner) can read or write it.
--
-- Money: USDT in micro-units (6 decimals), AFN in cents; timestamps are epoch milliseconds.

CREATE SCHEMA IF NOT EXISTS app;
SET search_path TO app;

CREATE TABLE users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text NOT NULL,
  phone text,
  phone_verified_at bigint,
  display_name text NOT NULL,
  password_hash text NOT NULL,
  password_changed_at bigint,
  role text NOT NULL DEFAULT 'user' CHECK (role IN ('user','admin','finance','support')),
  is_blocked integer NOT NULL DEFAULT 0,
  kyc_tier integer NOT NULL DEFAULT 0 CHECK (kyc_tier BETWEEN 0 AND 3),
  totp_secret text,
  totp_pending text,
  totp_enabled_at bigint,
  totp_last_step bigint NOT NULL DEFAULT 0,
  failed_logins integer NOT NULL DEFAULT 0,
  locked_until bigint NOT NULL DEFAULT 0,
  created_at bigint NOT NULL
);
CREATE UNIQUE INDEX users_username ON users (lower(username));
-- one verified phone number per account (limits multi-accounting)
CREATE UNIQUE INDEX users_verified_phone ON users (phone) WHERE phone_verified_at IS NOT NULL;

CREATE TABLE sessions (
  token text PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users(id),
  expires_at bigint NOT NULL
);
CREATE INDEX sessions_user ON sessions (user_id);

-- "locked" is held in escrow or for a pending withdrawal; neither can go negative.
CREATE TABLE balances (
  user_id bigint PRIMARY KEY REFERENCES users(id),
  available bigint NOT NULL DEFAULT 0 CHECK (available >= 0),
  locked bigint NOT NULL DEFAULT 0 CHECK (locked >= 0)
);

-- Append-only ledger. user_id NULL = platform (fees).
CREATE TABLE ledger (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint REFERENCES users(id),
  kind text NOT NULL,
  available_delta bigint NOT NULL,
  locked_delta bigint NOT NULL,
  ref_type text,
  ref_id bigint,
  created_at bigint NOT NULL
);
CREATE INDEX ledger_user ON ledger (user_id, id);

CREATE TABLE deposits (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users(id),
  amount bigint NOT NULL CHECK (amount > 0),
  network text NOT NULL,
  txid text NOT NULL,
  address text,
  source text NOT NULL DEFAULT 'manual' CHECK (source IN ('manual','chain')),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected')),
  note text,
  created_at bigint NOT NULL,
  reviewed_at bigint
);
CREATE UNIQUE INDEX deposits_txid_address ON deposits (txid, COALESCE(address, ''));
CREATE INDEX deposits_user ON deposits (user_id, id);

CREATE TABLE withdrawals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users(id),
  amount bigint NOT NULL CHECK (amount > 0),
  fee bigint NOT NULL,
  network text NOT NULL,
  address text NOT NULL,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','sending','sent','failed','rejected')),
  txid text,
  tx_expires_at bigint,
  auto integer NOT NULL DEFAULT 0,
  attempts integer NOT NULL DEFAULT 0,
  note text,
  created_at bigint NOT NULL,
  reviewed_at bigint
);
CREATE INDEX withdrawals_status ON withdrawals (status);
CREATE INDEX withdrawals_user ON withdrawals (user_id, id);
CREATE INDEX withdrawals_address ON withdrawals (address);

-- side: 'sell' = maker sells USDT (maker's USDT locked up front), 'buy' = maker buys USDT.
CREATE TABLE offers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users(id),
  side text NOT NULL CHECK (side IN ('buy','sell')),
  price bigint NOT NULL CHECK (price > 0),
  total bigint NOT NULL CHECK (total > 0),
  remaining bigint NOT NULL CHECK (remaining >= 0),
  min_fiat bigint NOT NULL,
  max_fiat bigint NOT NULL,
  payment_methods text NOT NULL,
  terms text NOT NULL DEFAULT '',
  payment_window integer NOT NULL,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','paused','closed')),
  created_at bigint NOT NULL
);
CREATE INDEX offers_market ON offers (status, side, price);
CREATE INDEX offers_user ON offers (user_id);

CREATE TABLE trades (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  offer_id bigint NOT NULL REFERENCES offers(id),
  maker_id bigint NOT NULL REFERENCES users(id),
  taker_id bigint NOT NULL REFERENCES users(id),
  buyer_id bigint NOT NULL REFERENCES users(id),
  seller_id bigint NOT NULL REFERENCES users(id),
  amount bigint NOT NULL CHECK (amount > 0),
  price bigint NOT NULL,
  fiat bigint NOT NULL,
  fee bigint NOT NULL,
  payment_method text NOT NULL,
  status text NOT NULL CHECK (status IN ('pending_payment','paid','disputed','completed','cancelled')),
  dispute_reason text,
  resolution text,
  expires_at bigint NOT NULL,
  paid_at bigint,
  closed_at bigint,
  created_at bigint NOT NULL
);
CREATE INDEX trades_buyer ON trades (buyer_id);
CREATE INDEX trades_seller ON trades (seller_id);
CREATE INDEX trades_taker ON trades (taker_id, status);
CREATE INDEX trades_status ON trades (status, expires_at);

CREATE TABLE trade_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trade_id bigint NOT NULL REFERENCES trades(id),
  user_id bigint REFERENCES users(id),
  body text NOT NULL,
  created_at bigint NOT NULL
);
CREATE INDEX messages_trade ON trade_messages (trade_id, id);

-- Where a user receives AFN for a given payment method (shown to the buyer of a trade).
CREATE TABLE payment_accounts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users(id),
  method text NOT NULL,
  holder_name text NOT NULL,
  account text NOT NULL,
  created_at bigint NOT NULL,
  UNIQUE (user_id, method)
);

-- Every staff decision, for accountability.
CREATE TABLE admin_actions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id bigint NOT NULL REFERENCES users(id),
  action text NOT NULL,
  target_type text NOT NULL,
  target_id bigint NOT NULL,
  note text,
  created_at bigint NOT NULL
);

-- TRON: per-user deposit addresses (HD index = user id).
CREATE TABLE deposit_addresses (
  user_id bigint PRIMARY KEY REFERENCES users(id),
  address text NOT NULL UNIQUE,
  derivation_index bigint NOT NULL UNIQUE,
  watch_until bigint NOT NULL DEFAULT 0,
  scanned_until bigint NOT NULL DEFAULT 0,
  last_scan_at bigint NOT NULL DEFAULT 0,
  needs_sweep integer NOT NULL DEFAULT 0,
  created_at bigint NOT NULL
);

-- Internal chain movements: TRX top-ups to deposit addresses and USDT sweeps out of them.
CREATE TABLE sweeps (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users(id),
  kind text NOT NULL CHECK (kind IN ('topup','sweep')),
  from_address text NOT NULL,
  to_address text NOT NULL,
  amount text NOT NULL,
  txid text NOT NULL,
  tx_expires_at bigint NOT NULL,
  status text NOT NULL CHECK (status IN ('sending','confirmed','failed')),
  note text,
  created_at bigint NOT NULL
);
CREATE INDEX sweeps_status ON sweeps (status);

CREATE TABLE otp_codes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users(id),
  purpose text NOT NULL,
  target text,
  code_hash text NOT NULL,
  attempts integer NOT NULL DEFAULT 0,
  expires_at bigint NOT NULL,
  used_at bigint,
  created_at bigint NOT NULL
);
CREATE INDEX otp_user ON otp_codes (user_id, purpose, id);

CREATE TABLE backup_codes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users(id),
  code_hash text NOT NULL,
  used_at bigint
);
CREATE INDEX backup_user ON backup_codes (user_id);

CREATE TABLE login_challenges (
  token_hash text PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users(id),
  attempts integer NOT NULL DEFAULT 0,
  expires_at bigint NOT NULL
);

CREATE TABLE security_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users(id),
  kind text NOT NULL,
  ip text,
  user_agent text,
  created_at bigint NOT NULL
);
CREATE INDEX security_events_user ON security_events (user_id, id);

CREATE TABLE kyc_submissions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users(id),
  doc_type text NOT NULL CHECK (doc_type IN ('tazkira','passport')),
  full_name text NOT NULL,
  doc_number text NOT NULL,
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','pending','approved','rejected')),
  tier_granted integer,
  reason text,
  reviewer_id bigint REFERENCES users(id),
  created_at bigint NOT NULL,
  submitted_at bigint,
  reviewed_at bigint
);
CREATE INDEX kyc_status ON kyc_submissions (status, id);
CREATE INDEX kyc_user ON kyc_submissions (user_id, id);

-- Document images are stored encrypted in object storage; only metadata lives here.
CREATE TABLE kyc_files (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submission_id bigint NOT NULL REFERENCES kyc_submissions(id),
  kind text NOT NULL CHECK (kind IN ('front','back','selfie')),
  path text NOT NULL,
  mime text NOT NULL,
  size integer NOT NULL,
  sha256 text NOT NULL,
  created_at bigint NOT NULL,
  UNIQUE (submission_id, kind)
);

CREATE TABLE alerts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users(id),
  rule text NOT NULL,
  severity text NOT NULL CHECK (severity IN ('info','low','medium','high')),
  details text NOT NULL,
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open','closed')),
  note text,
  closed_by bigint REFERENCES users(id),
  created_at bigint NOT NULL,
  closed_at bigint
);
CREATE INDEX alerts_status ON alerts (status, id);
CREATE UNIQUE INDEX alerts_one_open ON alerts (user_id, rule) WHERE status = 'open';

-- Lock the schema down: RLS on every table with no policies, and no privileges for Supabase's API roles.
DO $$
DECLARE t record;
BEGIN
  FOR t IN SELECT tablename FROM pg_tables WHERE schemaname = 'app' LOOP
    EXECUTE format('ALTER TABLE app.%I ENABLE ROW LEVEL SECURITY', t.tablename);
  END LOOP;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    EXECUTE 'REVOKE ALL ON SCHEMA app FROM anon, authenticated';
    EXECUTE 'REVOKE ALL ON ALL TABLES IN SCHEMA app FROM anon, authenticated';
    EXECUTE 'REVOKE ALL ON ALL SEQUENCES IN SCHEMA app FROM anon, authenticated';
    EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA app REVOKE ALL ON TABLES FROM anon, authenticated';
  END IF;
END $$;
REVOKE ALL ON SCHEMA app FROM PUBLIC;
