-- Phase 8: closed beta — invite codes, in-app feedback, error reports.
SET search_path TO app, public;

-- Invite codes. Only a keyed hash is stored; the code itself is shown once to the staff member who made it.
CREATE TABLE invites (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code_hash text NOT NULL UNIQUE,
  hint text NOT NULL,
  label text,
  max_uses integer NOT NULL CHECK (max_uses BETWEEN 1 AND 1000),
  uses integer NOT NULL DEFAULT 0 CHECK (uses >= 0 AND uses <= max_uses),
  expires_at bigint,
  revoked_at bigint,
  created_by bigint NOT NULL REFERENCES users(id),
  created_at bigint NOT NULL
);

ALTER TABLE users ADD COLUMN invite_id bigint REFERENCES invites(id);
CREATE INDEX users_invite ON users (invite_id);

-- Tester feedback; staff can answer, and the answer is shown to the user.
CREATE TABLE feedback (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users(id),
  kind text NOT NULL CHECK (kind IN ('bug','idea','question','other')),
  message text NOT NULL,
  page text,
  user_agent text,
  status text NOT NULL DEFAULT 'new' CHECK (status IN ('new','seen','done')),
  reply text,
  replied_by bigint REFERENCES users(id),
  replied_at bigint,
  created_at bigint NOT NULL
);
CREATE INDEX feedback_status ON feedback (status, id);
CREATE INDEX feedback_user ON feedback (user_id, id);

-- Errors from browsers and from the server, grouped by fingerprint.
CREATE TABLE app_errors (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fingerprint text NOT NULL UNIQUE,
  source text NOT NULL CHECK (source IN ('web','server')),
  message text NOT NULL,
  stack text,
  page text,
  user_agent text,
  user_id bigint REFERENCES users(id),
  count integer NOT NULL DEFAULT 1,
  first_seen bigint NOT NULL,
  last_seen bigint NOT NULL,
  resolved_at bigint
);
CREATE INDEX app_errors_open ON app_errors (resolved_at, last_seen);

-- Same rule as every table: RLS on, no policies, nothing for the Supabase API roles.
DO $$
DECLARE t record;
BEGIN
  FOR t IN SELECT tablename FROM pg_tables WHERE schemaname = 'app' LOOP
    EXECUTE format('ALTER TABLE app.%I ENABLE ROW LEVEL SECURITY', t.tablename);
  END LOOP;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    EXECUTE 'REVOKE ALL ON ALL TABLES IN SCHEMA app FROM anon, authenticated';
    EXECUTE 'REVOKE ALL ON ALL SEQUENCES IN SCHEMA app FROM anon, authenticated';
  END IF;
END $$;
